# 1 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 2 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Frlg_MapScripts::
# 3 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 5 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 6 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_RestHouseSign::
# 7 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 4 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 8 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_RestHouse, MSGBOX_SIGN
# 9 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 10 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 11 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 12 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_TrainerTips1::
# 13 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 9 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 14 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_SecretHouseStillAhead, MSGBOX_SIGN
# 15 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 16 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 17 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 18 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_AreaSign::
# 19 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 14 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 20 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_Area2, MSGBOX_SIGN
# 21 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 22 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 23 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 24 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_TrainerTips2::
# 25 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 19 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 26 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_ZigzagThroughTallGrass, MSGBOX_SIGN
# 27 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 28 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 29 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 30 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_EventScript_TrainerTips3::
# 31 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 24 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 32 "data/maps/SafariZone_North_Frlg/scripts.pory"
	msgbox SafariZone_North_Text_WinFreeHMFindSecretHouse, MSGBOX_SIGN
# 33 "data/maps/SafariZone_North_Frlg/scripts.pory"
	end
# 34 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 35 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 36 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_RestHouse::
# 37 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 28 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 38 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "REST HOUSE$"
# 39 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 40 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_SecretHouseStillAhead::
# 41 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 32 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 42 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 43 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "The SECRET HOUSE is still ahead.$"
# 44 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 45 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_Area2::
# 46 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 37 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 47 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "AREA 2$"
# 48 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 49 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_ZigzagThroughTallGrass::
# 50 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 41 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 51 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 52 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "POKéMON hide in tall grass.\p"
# 53 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "Zigzag through grassy areas to\n"
# 54 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "flush them out.$"
# 55 "data/maps/SafariZone_North_Frlg/scripts.pory"

# 56 "data/maps/SafariZone_North_Frlg/scripts.pory"
SafariZone_North_Text_WinFreeHMFindSecretHouse::
# 57 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 48 "data/maps/SafariZone_North_Frlg/scripts.pory"
# 58 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 59 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "Win a free HM for finding the\n"
# 60 "data/maps/SafariZone_North_Frlg/scripts.pory"
	.string "SECRET HOUSE.$"
