BattleFrontier_Lounge8_MapScripts::
	.byte 0


BattleFrontier_Lounge8_EventScript_Man::
# 4 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end


BattleFrontier_Lounge8_EventScript_Woman::
# 9 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end


BattleFrontier_Lounge8_EventScript_NinjaBoy::
# 14 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end


BattleFrontier_Lounge8_Text_WhatATrainerNeeds::
# 18 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "What a TRAINER needs…\p"
	.string "Knowledge…\n"
	.string "Strategy…\l"
	.string "Luck…\l"
	.string "Guts…\l"
	.string "Spirit…\l"
	.string "Bravery…\l"
	.string "And ability…\p"
	.string "Well, I'm all set in every way!\n"
	.string "I'll be unstoppable at every building!\p"
	.string "Huh? POKéMON?\n"
	.string "What's that?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains::
# 33 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Do you know about the FRONTIER\n"
	.string "BRAINS?\p"
	.string "That's what SCOTT calls the seven\n"
	.string "special TRAINERS that run the seven\l"
	.string "facilities in the BATTLE FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling::
# 41 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "At the BATTLE TOWER, an older girl\n"
	.string "told me that I have a lot of talent\l"
	.string "for battling!\p"
	.string "I like POKéMON CONTESTS more!\p"
	.string "But I'm no good at CONTESTS!\p"
	.string "I guess having talent and liking\n"
	.string "something aren't the same.$"
