# 1 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 2 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_MapScripts::
# 3 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 5 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 6 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_EventScript_Man::
# 7 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
# 4 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
# 8 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	msgbox RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility, MSGBOX_NPC
# 9 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	end
# 10 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 11 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 12 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_EventScript_Woman::
# 13 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
# 9 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
# 14 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	msgbox RustboroCity_Flat1_1F_Text_PokemonStrange, MSGBOX_NPC
# 15 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	end
# 16 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 17 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 18 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility::
# 19 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
# 13 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
# 20 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "Every POKéMON has a special ability\n"
# 21 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "that it can use.$"
# 22 "data/maps/RustboroCity_Flat1_1F/scripts.pory"

# 23 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
RustboroCity_Flat1_1F_Text_PokemonStrange::
# 24 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
# 18 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
# 25 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "POKéMON are such strange creatures.$"
