# 1 "data/maps/OneIsland_House1_Frlg/scripts.pory"

# 2 "data/maps/OneIsland_House1_Frlg/scripts.pory"
OneIsland_House1_Frlg_MapScripts::
# 3 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_House1_Frlg/scripts.pory"

# 5 "data/maps/OneIsland_House1_Frlg/scripts.pory"

# 6 "data/maps/OneIsland_House1_Frlg/scripts.pory"
OneIsland_House1_EventScript_OldMan::
# 7 "data/maps/OneIsland_House1_Frlg/scripts.pory"
# 4 "data/maps/OneIsland_House1_Frlg/scripts.pory"
# 8 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
# 9 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	end
# 10 "data/maps/OneIsland_House1_Frlg/scripts.pory"

# 11 "data/maps/OneIsland_House1_Frlg/scripts.pory"

# 12 "data/maps/OneIsland_House1_Frlg/scripts.pory"
OneIsland_House1_EventScript_OldWoman::
# 13 "data/maps/OneIsland_House1_Frlg/scripts.pory"
# 9 "data/maps/OneIsland_House1_Frlg/scripts.pory"
# 14 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
# 15 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	end
# 16 "data/maps/OneIsland_House1_Frlg/scripts.pory"

# 17 "data/maps/OneIsland_House1_Frlg/scripts.pory"

# 18 "data/maps/OneIsland_House1_Frlg/scripts.pory"
OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
# 19 "data/maps/OneIsland_House1_Frlg/scripts.pory"
# 13 "data/maps/OneIsland_House1_Frlg/scripts.pory"
# 20 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	.string "On sunny days, I step out and gaze\n"
# 21 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	.string "upon the volcano.\p"
# 22 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	.string "That's my daily routine.$"
# 23 "data/maps/OneIsland_House1_Frlg/scripts.pory"

# 24 "data/maps/OneIsland_House1_Frlg/scripts.pory"
OneIsland_House1_Text_LastTimeMtEmberErupted::
# 25 "data/maps/OneIsland_House1_Frlg/scripts.pory"
# 19 "data/maps/OneIsland_House1_Frlg/scripts.pory"
# 26 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	.string "Let me think… When was the last\n"
# 27 "data/maps/OneIsland_House1_Frlg/scripts.pory"
	.string "time MT. EMBER erupted?$"
