Route9_Frlg_MapScripts::
	.byte 0


Route9_EventScript_RouteSign::
# 4 "data/maps/Route9_Frlg/scripts.pory"
	msgbox Route9_Text_RouteSign, MSGBOX_SIGN
	end


Route9_Text_AliciaIntro::
# 8 "data/maps/Route9_Frlg/scripts.pory"
	.string "You have POKéMON with you!\n"
	.string "You're mine!$"

Route9_Text_AliciaDefeat::
# 13 "data/maps/Route9_Frlg/scripts.pory"
	.string "You deceived me…$"

Route9_Text_AliciaPostBattle::
# 17 "data/maps/Route9_Frlg/scripts.pory"
	.string "The tunnel coming up is pitch-black\n"
	.string "inside.\p"
	.string "You'll need FLASH to get through\n"
	.string "there.$"

Route9_Text_ChrisIntro::
# 24 "data/maps/Route9_Frlg/scripts.pory"
	.string "Who's that walking there with those\n"
	.string "good-looking POKéMON?$"

Route9_Text_ChrisDefeat::
# 29 "data/maps/Route9_Frlg/scripts.pory"
	.string "Out like a light!$"

Route9_Text_ChrisPostBattle::
# 33 "data/maps/Route9_Frlg/scripts.pory"
	.string "Keep walking!$"

Route9_Text_DrewIntro::
# 37 "data/maps/Route9_Frlg/scripts.pory"
	.string "I'm taking the ROCK TUNNEL to\n"
	.string "go to LAVENDER…$"

Route9_Text_DrewDefeat::
# 42 "data/maps/Route9_Frlg/scripts.pory"
	.string "Can't measure up…$"

Route9_Text_DrewPostBattle::
# 46 "data/maps/Route9_Frlg/scripts.pory"
	.string "Are you off to ROCK TUNNEL, too?$"

Route9_Text_CaitlinIntro::
# 50 "data/maps/Route9_Frlg/scripts.pory"
	.string "Don't you dare patronize me!$"

Route9_Text_CaitlinDefeat::
# 54 "data/maps/Route9_Frlg/scripts.pory"
	.string "No!\n"
	.string "You're too much.$"

Route9_Text_CaitlinPostBattle::
# 59 "data/maps/Route9_Frlg/scripts.pory"
	.string "You're obviously talented.\n"
	.string "Good luck to you!$"

Route9_Text_JeremyIntro::
# 64 "data/maps/Route9_Frlg/scripts.pory"
	.string "Bwahaha!\n"
	.string "Great! I was bored, eh!$"

Route9_Text_JeremyDefeat::
# 69 "data/maps/Route9_Frlg/scripts.pory"
	.string "Keep it coming, eh!\p"
	.string "Oh wait.\n"
	.string "I'm out of POKéMON!$"

Route9_Text_JeremyPostBattle::
# 75 "data/maps/Route9_Frlg/scripts.pory"
	.string "You sure had guts standing up to\n"
	.string "me there, eh?$"

Route9_Text_BriceIntro::
# 80 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahaha!\n"
	.string "Aren't you a little toughie!$"

Route9_Text_BriceDefeat::
# 85 "data/maps/Route9_Frlg/scripts.pory"
	.string "What's that?$"

Route9_Text_BricePostBattle::
# 89 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahaha!\n"
	.string "Kids should be tough!$"

Route9_Text_BrentIntro::
# 94 "data/maps/Route9_Frlg/scripts.pory"
	.string "I got up early every day to raise\n"
	.string "my POKéMON from cocoons!$"

Route9_Text_BrentDefeat::
# 99 "data/maps/Route9_Frlg/scripts.pory"
	.string "WHAT?\p"
	.string "What a total waste of time!$"

Route9_Text_BrentPostBattle::
# 104 "data/maps/Route9_Frlg/scripts.pory"
	.string "I have to collect more than bugs\n"
	.string "to get stronger…$"

Route9_Text_AlanIntro::
# 109 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahahaha!\n"
	.string "Bring it on!$"

Route9_Text_AlanDefeat::
# 114 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahahaha!\n"
	.string "You beat me fair!$"

Route9_Text_AlanPostBattle::
# 119 "data/maps/Route9_Frlg/scripts.pory"
	.string "Hahahaha!\n"
	.string "Us hearty guys always laugh!$"

Route9_Text_ConnerIntro::
# 124 "data/maps/Route9_Frlg/scripts.pory"
	.string "Go, my super BUG POKéMON!$"

Route9_Text_ConnerDefeat::
# 128 "data/maps/Route9_Frlg/scripts.pory"
	.string "My bugs…$"

Route9_Text_ConnerPostBattle::
# 132 "data/maps/Route9_Frlg/scripts.pory"
	.string "If you don't like BUG POKéMON,\n"
	.string "you bug me!$"

Route9_Text_RouteSign::
# 137 "data/maps/Route9_Frlg/scripts.pory"
	.string "ROUTE 9\n"
	.string "CERULEAN CITY - ROCK TUNNEL$"
