# 1 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 2 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_Frlg_MapScripts::
# 3 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 5 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 6 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_EventScript_RestHouseSign::
# 7 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 4 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 8 "data/maps/SafariZone_West_Frlg/scripts.pory"
	msgbox SafariZone_West_Text_RestHouse, MSGBOX_SIGN
# 9 "data/maps/SafariZone_West_Frlg/scripts.pory"
	end
# 10 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 11 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 12 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_EventScript_LostTeethNotice::
# 13 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 9 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 14 "data/maps/SafariZone_West_Frlg/scripts.pory"
	msgbox SafariZone_West_Text_PleaseFindWardensLostTeeth, MSGBOX_SIGN
# 15 "data/maps/SafariZone_West_Frlg/scripts.pory"
	end
# 16 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 17 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 18 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_EventScript_TrainerTips::
# 19 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 14 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 20 "data/maps/SafariZone_West_Frlg/scripts.pory"
	msgbox SafariZone_West_Text_SearchForSecretHouse, MSGBOX_SIGN
# 21 "data/maps/SafariZone_West_Frlg/scripts.pory"
	end
# 22 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 23 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 24 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_EventScript_AreaSign::
# 25 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 19 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 26 "data/maps/SafariZone_West_Frlg/scripts.pory"
	msgbox SafariZone_West_Text_AreaSign, MSGBOX_SIGN
# 27 "data/maps/SafariZone_West_Frlg/scripts.pory"
	end
# 28 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 29 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 30 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_Text_RestHouse::
# 31 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 23 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 32 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "REST HOUSE$"
# 33 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 34 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_Text_PleaseFindWardensLostTeeth::
# 35 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 27 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 36 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "REQUEST NOTICE\p"
# 37 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "Please find the SAFARI WARDEN's\n"
# 38 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "lost GOLD TEETH.\l"
# 39 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "They're around here somewhere.\p"
# 40 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "Reward offered!\n"
# 41 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "Contact: WARDEN$"
# 42 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 43 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_Text_SearchForSecretHouse::
# 44 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 36 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 45 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
# 46 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "Zone Exploration Campaign!\n"
# 47 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "The Search for the SECRET HOUSE!$"
# 48 "data/maps/SafariZone_West_Frlg/scripts.pory"

# 49 "data/maps/SafariZone_West_Frlg/scripts.pory"
SafariZone_West_Text_AreaSign::
# 50 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 42 "data/maps/SafariZone_West_Frlg/scripts.pory"
# 51 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "AREA 3\n"
# 52 "data/maps/SafariZone_West_Frlg/scripts.pory"
	.string "EAST: CENTER AREA$"
