# 1 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"

# 2 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
UndergroundPath_NorthSouthTunnel_Frlg_MapScripts::
# 3 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
# 2 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
# 4 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, UndergroundPath_NorthSouthTunnel_OnTransition
# 5 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
	.byte 0
# 6 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"

# 7 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"

# 8 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
UndergroundPath_NorthSouthTunnel_OnTransition::
# 9 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
# 6 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
# 10 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
	setworldmapflag FLAG_WORLD_MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL
# 11 "data/maps/UndergroundPath_NorthSouthTunnel_Frlg/scripts.pory"
	end
