# 1 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 2 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Frlg_MapScripts::
# 3 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 5 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 6 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Sofia::
# 7 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 4 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 8 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_SOFIA, RockTunnel_B1F_Text_SofiaIntro, RockTunnel_B1F_Text_SofiaDefeat
# 9 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 5 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 10 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_SofiaPostBattle, MSGBOX_AUTOCLOSE
# 11 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 12 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 13 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 14 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Martha::
# 15 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 10 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 16 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_PICNICKER_MARTHA, RockTunnel_B1F_Text_MarthaIntro, RockTunnel_B1F_Text_MarthaDefeat
# 17 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 11 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 18 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_MarthaPostBattle, MSGBOX_AUTOCLOSE
# 19 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 20 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 21 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 22 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Dudley::
# 23 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 16 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 24 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_HIKER_DUDLEY, RockTunnel_B1F_Text_DudleyIntro, RockTunnel_B1F_Text_DudleyDefeat
# 25 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 17 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 26 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_DudleyPostBattle, MSGBOX_AUTOCLOSE
# 27 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 28 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 29 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 30 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Allen::
# 31 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 22 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 32 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ALLEN, RockTunnel_B1F_Text_AllenIntro, RockTunnel_B1F_Text_AllenDefeat
# 33 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 23 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 34 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_AllenPostBattle, MSGBOX_AUTOCLOSE
# 35 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 36 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 37 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 38 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Eric::
# 39 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 28 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 40 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_HIKER_ERIC, RockTunnel_B1F_Text_EricIntro, RockTunnel_B1F_Text_EricDefeat
# 41 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 29 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 42 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_EricPostBattle, MSGBOX_AUTOCLOSE
# 43 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 44 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 45 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 46 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Cooper::
# 47 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 34 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 48 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_COOPER, RockTunnel_B1F_Text_CooperIntro, RockTunnel_B1F_Text_CooperDefeat
# 49 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 35 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 50 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_CooperPostBattle, MSGBOX_AUTOCLOSE
# 51 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 52 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 53 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 54 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Steve::
# 55 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 40 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 56 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_STEVE, RockTunnel_B1F_Text_SteveIntro, RockTunnel_B1F_Text_SteveDefeat
# 57 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 41 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 58 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_StevePostBattle, MSGBOX_AUTOCLOSE
# 59 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 60 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 61 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 62 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_EventScript_Winston::
# 63 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 46 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 64 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	trainerbattle_single TRAINER_POKEMANIAC_WINSTON, RockTunnel_B1F_Text_WinstonIntro, RockTunnel_B1F_Text_WinstonDefeat
# 65 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 47 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 66 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	msgbox RockTunnel_B1F_Text_WinstonPostBattle, MSGBOX_AUTOCLOSE
# 67 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	end
# 68 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 69 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 70 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SofiaIntro::
# 71 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 51 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 72 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Do you know how you can avoid\n"
# 73 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "getting lost in the mountains?\p"
# 74 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "You can bend twigs as trail\n"
# 75 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "markers.$"
# 76 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 77 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SofiaDefeat::
# 78 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 58 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 79 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Ohhh!\n"
# 80 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I did my best!$"
# 81 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 82 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SofiaPostBattle::
# 83 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 63 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 84 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I want to go home!$"
# 85 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 86 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_DudleyIntro::
# 87 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 67 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 88 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Hahaha!\n"
# 89 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Can you beat my power?$"
# 90 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 91 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_DudleyDefeat::
# 92 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 72 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 93 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Oops!\n"
# 94 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Outmuscled!$"
# 95 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 96 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_DudleyPostBattle::
# 97 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 77 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 98 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I go for power because I hate\n"
# 99 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "thinking.$"
# 100 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 101 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_CooperIntro::
# 102 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 82 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 103 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "You have a POKéDEX?\n"
# 104 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I want one, too.$"
# 105 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 106 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_CooperDefeat::
# 107 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 87 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 108 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Shoot!\n"
# 109 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I am so jealous!$"
# 110 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 111 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_CooperPostBattle::
# 112 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 92 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 113 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "When you finish your POKéDEX,\n"
# 114 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "can I have it?$"
# 115 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 116 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SteveIntro::
# 117 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 97 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 118 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Um… Do you know about POKéMON\n"
# 119 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "cosplay?$"
# 120 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 121 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_SteveDefeat::
# 122 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 102 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 123 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Well, that's that.$"
# 124 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 125 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_StevePostBattle::
# 126 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 106 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 127 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "POKéMON cosplay is dressing up as\n"
# 128 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "POKéMON for fun.\p"
# 129 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "CLEFAIRY is a favorite.$"
# 130 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 131 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_AllenIntro::
# 132 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 112 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 133 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "My POKéMON techniques will leave\n"
# 134 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "you crying!$"
# 135 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 136 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_AllenDefeat::
# 137 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 117 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 138 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I give!\n"
# 139 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "You're a better technician!$"
# 140 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 141 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_AllenPostBattle::
# 142 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 122 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 143 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "In mountains, you'll often find\n"
# 144 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "ROCK-type POKéMON.$"
# 145 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 146 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_MarthaIntro::
# 147 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 127 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 148 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I don't often come here, but I will\n"
# 149 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "battle you.$"
# 150 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 151 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_MarthaDefeat::
# 152 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 132 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 153 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Oh!\n"
# 154 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I lost!$"
# 155 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 156 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_MarthaPostBattle::
# 157 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 137 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 158 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I like tiny POKéMON.\n"
# 159 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Big ones are too scary!$"
# 160 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 161 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_EricIntro::
# 162 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 142 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 163 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Hit me with your best shot!$"
# 164 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 165 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_EricDefeat::
# 166 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 146 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 167 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Fired away!$"
# 168 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 169 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_EricPostBattle::
# 170 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 150 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 171 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I'll raise my POKéMON to beat\n"
# 172 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "yours, kid.$"
# 173 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 174 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_WinstonIntro::
# 175 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 155 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 176 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I draw illustrations of POKéMON\n"
# 177 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "when I'm home.$"
# 178 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 179 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_WinstonDefeat::
# 180 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 160 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 181 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "Whew…\n"
# 182 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I'm exhausted…$"
# 183 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"

# 184 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
RockTunnel_B1F_Text_WinstonPostBattle::
# 185 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 165 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
# 186 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I'm an artist, not a fighter.\n"
# 187 "data/maps/RockTunnel_B1F_Frlg/scripts.pory"
	.string "I'll go home to draw.$"
