gText_Birch_Welcome::
        .string "Urgh… Where am I?\p"
        .string "I can't seem to remember…\p"
        .string "Who is that man?\n"
        .string "He seems familiar…\p"
        .string "Who… am I?\p"
        .string "$"


gText_Birch_Pokemon::
        .string "I remember a strange POKéMON…\p"
        .string "\n"
        .string "$"


gText_Birch_MainSpeech::
        .string "But that POKéMON looks strange…\p"
        .string "I think something terrible\n"
        .string "has happened.\p"
        .string "Is it just my memory playing\n"
        .string "tricks on me…\p"
        .string "Or was that POKéMON I saw…\n"
        .string "dead?\p"
        .string "That can't be right, surely?\n"
        .string "POKéMON don't die.\l"
        .string "They just faint… right?\p"
        .string "But I'm sure that's what I saw.\p"
        .string "$"


gText_Birch_AndYouAre::
        .string "Wait… who am I?$"


gText_Birch_BoyOrGirl::
        .string "Am I a boy?\n"
        .string "Or a girl?$"


gText_Birch_WhatsYourName::
        .string "All right.\n"
        .string "And my name is?$"


gText_Birch_SoItsPlayer::
        .string "Yeah… it's {PLAYER}?$"


gText_Birch_YourePlayer::
        .string "I've got it!\p"
        .string "I'm {PLAYER}.\n"
        .string "I live in LITTLEROOT TOWN.\p"
        .string "I remember now!\p"
        .string "$"

		
gText_Birch_AreYouReady::
        .string "I need to figure out\n"
        .string "where I am.\p"
        .string "What happened here.\p"
        .string "And why I'm the only one\n"
        .string "still standing.\p"
        .string "$"
