# 1 "data/maps/Route4_Frlg/scripts.pory"

# 2 "data/maps/Route4_Frlg/scripts.pory"
Route4_Frlg_MapScripts::
# 3 "data/maps/Route4_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route4_Frlg/scripts.pory"

# 5 "data/maps/Route4_Frlg/scripts.pory"

# 6 "data/maps/Route4_Frlg/scripts.pory"
Route4_EventScript_Unused::
# 7 "data/maps/Route4_Frlg/scripts.pory"
	end
# 8 "data/maps/Route4_Frlg/scripts.pory"

# 9 "data/maps/Route4_Frlg/scripts.pory"

# 10 "data/maps/Route4_Frlg/scripts.pory"
Route4_EventScript_Woman::
# 11 "data/maps/Route4_Frlg/scripts.pory"
# 8 "data/maps/Route4_Frlg/scripts.pory"
# 12 "data/maps/Route4_Frlg/scripts.pory"
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
# 13 "data/maps/Route4_Frlg/scripts.pory"
	end
# 14 "data/maps/Route4_Frlg/scripts.pory"

# 15 "data/maps/Route4_Frlg/scripts.pory"

# 16 "data/maps/Route4_Frlg/scripts.pory"
Route4_EventScript_MtMoonSign::
# 17 "data/maps/Route4_Frlg/scripts.pory"
# 13 "data/maps/Route4_Frlg/scripts.pory"
# 18 "data/maps/Route4_Frlg/scripts.pory"
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
# 19 "data/maps/Route4_Frlg/scripts.pory"
	end
# 20 "data/maps/Route4_Frlg/scripts.pory"

# 21 "data/maps/Route4_Frlg/scripts.pory"

# 22 "data/maps/Route4_Frlg/scripts.pory"
Route4_EventScript_RouteSign::
# 23 "data/maps/Route4_Frlg/scripts.pory"
# 18 "data/maps/Route4_Frlg/scripts.pory"
# 24 "data/maps/Route4_Frlg/scripts.pory"
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
# 25 "data/maps/Route4_Frlg/scripts.pory"
	end
# 26 "data/maps/Route4_Frlg/scripts.pory"

# 27 "data/maps/Route4_Frlg/scripts.pory"

# 28 "data/maps/Route4_Frlg/scripts.pory"
Route4_Text_TrippedOverGeodude::
# 29 "data/maps/Route4_Frlg/scripts.pory"
# 22 "data/maps/Route4_Frlg/scripts.pory"
# 30 "data/maps/Route4_Frlg/scripts.pory"
	.string "Ouch! I tripped over a rocky\n"
# 31 "data/maps/Route4_Frlg/scripts.pory"
	.string "POKéMON, GEODUDE!$"
# 32 "data/maps/Route4_Frlg/scripts.pory"

# 33 "data/maps/Route4_Frlg/scripts.pory"
Route4_Text_CrissyIntro::
# 34 "data/maps/Route4_Frlg/scripts.pory"
# 27 "data/maps/Route4_Frlg/scripts.pory"
# 35 "data/maps/Route4_Frlg/scripts.pory"
	.string "I came to MT. MOON in search of\n"
# 36 "data/maps/Route4_Frlg/scripts.pory"
	.string "mushroom POKéMON.$"
# 37 "data/maps/Route4_Frlg/scripts.pory"

# 38 "data/maps/Route4_Frlg/scripts.pory"
Route4_Text_CrissyDefeat::
# 39 "data/maps/Route4_Frlg/scripts.pory"
# 32 "data/maps/Route4_Frlg/scripts.pory"
# 40 "data/maps/Route4_Frlg/scripts.pory"
	.string "After all I did to catch them!$"
# 41 "data/maps/Route4_Frlg/scripts.pory"

# 42 "data/maps/Route4_Frlg/scripts.pory"
Route4_Text_CrissyPostBattle::
# 43 "data/maps/Route4_Frlg/scripts.pory"
# 36 "data/maps/Route4_Frlg/scripts.pory"
# 44 "data/maps/Route4_Frlg/scripts.pory"
	.string "There might not be any more\n"
# 45 "data/maps/Route4_Frlg/scripts.pory"
	.string "mushrooms here.\p"
# 46 "data/maps/Route4_Frlg/scripts.pory"
	.string "I think I got them all.$"
# 47 "data/maps/Route4_Frlg/scripts.pory"

# 48 "data/maps/Route4_Frlg/scripts.pory"
Route4_Text_MtMoonEntrance::
# 49 "data/maps/Route4_Frlg/scripts.pory"
# 42 "data/maps/Route4_Frlg/scripts.pory"
# 50 "data/maps/Route4_Frlg/scripts.pory"
	.string "MT. MOON\n"
# 51 "data/maps/Route4_Frlg/scripts.pory"
	.string "Tunnel Entrance$"
# 52 "data/maps/Route4_Frlg/scripts.pory"

# 53 "data/maps/Route4_Frlg/scripts.pory"
Route4_Text_RouteSign::
# 54 "data/maps/Route4_Frlg/scripts.pory"
# 47 "data/maps/Route4_Frlg/scripts.pory"
# 55 "data/maps/Route4_Frlg/scripts.pory"
	.string "ROUTE 4\n"
# 56 "data/maps/Route4_Frlg/scripts.pory"
	.string "MT. MOON - CERULEAN CITY$"
# 57 "data/maps/Route4_Frlg/scripts.pory"

# 58 "data/maps/Route4_Frlg/scripts.pory"
Text_MegaPunchTeach::
# 59 "data/maps/Route4_Frlg/scripts.pory"
# 52 "data/maps/Route4_Frlg/scripts.pory"
# 60 "data/maps/Route4_Frlg/scripts.pory"
	.string "A punch of roaring ferocity!\p"
# 61 "data/maps/Route4_Frlg/scripts.pory"
	.string "Packed with destructive power!\p"
# 62 "data/maps/Route4_Frlg/scripts.pory"
	.string "When the chips are down,\n"
# 63 "data/maps/Route4_Frlg/scripts.pory"
	.string "MEGA PUNCH is the ultimate attack!\l"
# 64 "data/maps/Route4_Frlg/scripts.pory"
	.string "You agree, yes?\p"
# 65 "data/maps/Route4_Frlg/scripts.pory"
	.string "Now!\n"
# 66 "data/maps/Route4_Frlg/scripts.pory"
	.string "Let me teach it to your POKéMON!$"
# 67 "data/maps/Route4_Frlg/scripts.pory"

# 68 "data/maps/Route4_Frlg/scripts.pory"
Text_MegaPunchDeclined::
# 69 "data/maps/Route4_Frlg/scripts.pory"
# 62 "data/maps/Route4_Frlg/scripts.pory"
# 70 "data/maps/Route4_Frlg/scripts.pory"
	.string "You'll be back when you understand\n"
# 71 "data/maps/Route4_Frlg/scripts.pory"
	.string "the worth of MEGA PUNCH.$"
# 72 "data/maps/Route4_Frlg/scripts.pory"

# 73 "data/maps/Route4_Frlg/scripts.pory"
Text_MegaPunchWhichMon::
# 74 "data/maps/Route4_Frlg/scripts.pory"
# 67 "data/maps/Route4_Frlg/scripts.pory"
# 75 "data/maps/Route4_Frlg/scripts.pory"
	.string "Fine!\n"
# 76 "data/maps/Route4_Frlg/scripts.pory"
	.string "Which POKéMON will learn it?$"
# 77 "data/maps/Route4_Frlg/scripts.pory"

# 78 "data/maps/Route4_Frlg/scripts.pory"
Text_MegaPunchTaught::
# 79 "data/maps/Route4_Frlg/scripts.pory"
# 72 "data/maps/Route4_Frlg/scripts.pory"
# 80 "data/maps/Route4_Frlg/scripts.pory"
	.string "Now, we are comrades in the way of\n"
# 81 "data/maps/Route4_Frlg/scripts.pory"
	.string "punching!\p"
# 82 "data/maps/Route4_Frlg/scripts.pory"
	.string "You should go before you're seen\n"
# 83 "data/maps/Route4_Frlg/scripts.pory"
	.string "by the misguided fool who trains\l"
# 84 "data/maps/Route4_Frlg/scripts.pory"
	.string "only his silly kicking over there.$"
# 85 "data/maps/Route4_Frlg/scripts.pory"

# 86 "data/maps/Route4_Frlg/scripts.pory"
Text_MegaKickTeach::
# 87 "data/maps/Route4_Frlg/scripts.pory"
# 80 "data/maps/Route4_Frlg/scripts.pory"
# 88 "data/maps/Route4_Frlg/scripts.pory"
	.string "A kick of brutal ferocity!\p"
# 89 "data/maps/Route4_Frlg/scripts.pory"
	.string "Packed with destructive power!\p"
# 90 "data/maps/Route4_Frlg/scripts.pory"
	.string "When you get right down to it,\n"
# 91 "data/maps/Route4_Frlg/scripts.pory"
	.string "MEGA KICK is the ultimate attack!\l"
# 92 "data/maps/Route4_Frlg/scripts.pory"
	.string "Don't you agree?\p"
# 93 "data/maps/Route4_Frlg/scripts.pory"
	.string "Okay!\n"
# 94 "data/maps/Route4_Frlg/scripts.pory"
	.string "I'll teach it to your POKéMON!$"
# 95 "data/maps/Route4_Frlg/scripts.pory"

# 96 "data/maps/Route4_Frlg/scripts.pory"
Text_MegaKickDeclined::
# 97 "data/maps/Route4_Frlg/scripts.pory"
# 90 "data/maps/Route4_Frlg/scripts.pory"
# 98 "data/maps/Route4_Frlg/scripts.pory"
	.string "You'll come crawling back when you\n"
# 99 "data/maps/Route4_Frlg/scripts.pory"
	.string "realize the value of MEGA KICK.$"
# 100 "data/maps/Route4_Frlg/scripts.pory"

# 101 "data/maps/Route4_Frlg/scripts.pory"
Text_MegaKickWhichMon::
# 102 "data/maps/Route4_Frlg/scripts.pory"
# 95 "data/maps/Route4_Frlg/scripts.pory"
# 103 "data/maps/Route4_Frlg/scripts.pory"
	.string "All right!\n"
# 104 "data/maps/Route4_Frlg/scripts.pory"
	.string "Which POKéMON wants to learn it?$"
# 105 "data/maps/Route4_Frlg/scripts.pory"

# 106 "data/maps/Route4_Frlg/scripts.pory"
Text_MegaKickTaught::
# 107 "data/maps/Route4_Frlg/scripts.pory"
# 100 "data/maps/Route4_Frlg/scripts.pory"
# 108 "data/maps/Route4_Frlg/scripts.pory"
	.string "Now, we are soul mates in the way\n"
# 109 "data/maps/Route4_Frlg/scripts.pory"
	.string "of kicking!\p"
# 110 "data/maps/Route4_Frlg/scripts.pory"
	.string "You should run before you're seen\n"
# 111 "data/maps/Route4_Frlg/scripts.pory"
	.string "by the deluded nitwit who trains\l"
# 112 "data/maps/Route4_Frlg/scripts.pory"
	.string "only simple punching over there.$"
# 113 "data/maps/Route4_Frlg/scripts.pory"

# 114 "data/maps/Route4_Frlg/scripts.pory"
Route4_Text_PeopleLikeAndRespectBrock::
# 115 "data/maps/Route4_Frlg/scripts.pory"
# 108 "data/maps/Route4_Frlg/scripts.pory"
# 116 "data/maps/Route4_Frlg/scripts.pory"
	.string "Oh, wow, that's the BOULDERBADGE!\n"
# 117 "data/maps/Route4_Frlg/scripts.pory"
	.string "You got it from BROCK, didn't you?\p"
# 118 "data/maps/Route4_Frlg/scripts.pory"
	.string "BROCK is cool. He's not just tough.\n"
# 119 "data/maps/Route4_Frlg/scripts.pory"
	.string "People like and respect him.\p"
# 120 "data/maps/Route4_Frlg/scripts.pory"
	.string "I want to become a GYM LEADER\n"
# 121 "data/maps/Route4_Frlg/scripts.pory"
	.string "like him.$"
