Route19_Frlg_MapScripts::
	.byte 0


Route19_EventScript_RouteSign::
# 4 "data/maps/Route19_Frlg/scripts.pory"
	msgbox Route19_Text_RouteSign, MSGBOX_SIGN
	end


Route19_Text_RichardIntro::
# 8 "data/maps/Route19_Frlg/scripts.pory"
	.string "I have to exercise and warm up\n"
	.string "before going out for a swim.$"

Route19_Text_RichardDefeat::
# 13 "data/maps/Route19_Frlg/scripts.pory"
	.string "All warmed up!$"

Route19_Text_RichardPostBattle::
# 17 "data/maps/Route19_Frlg/scripts.pory"
	.string "Thanks, kid!\n"
	.string "I'm ready for a swim.$"

Route19_Text_ReeceIntro::
# 22 "data/maps/Route19_Frlg/scripts.pory"
	.string "Wait! Slow down!\n"
	.string "You'll have a heart attack!$"

Route19_Text_ReeceDefeat::
# 27 "data/maps/Route19_Frlg/scripts.pory"
	.string "Ooh!\n"
	.string "That's chilly!$"

Route19_Text_ReecePostBattle::
# 32 "data/maps/Route19_Frlg/scripts.pory"
	.string "Watch out for TENTACOOL.\n"
	.string "They sting so painfully.$"

Route19_Text_MatthewIntro::
# 37 "data/maps/Route19_Frlg/scripts.pory"
	.string "I love swimming!\n"
	.string "What about you?$"

Route19_Text_MatthewDefeat::
# 42 "data/maps/Route19_Frlg/scripts.pory"
	.string "Belly flop!$"

Route19_Text_MatthewPostBattle::
# 46 "data/maps/Route19_Frlg/scripts.pory"
	.string "I can beat even marine POKéMON\n"
	.string "at swimming.$"

Route19_Text_DouglasIntro::
# 51 "data/maps/Route19_Frlg/scripts.pory"
	.string "What's beyond the horizon?$"

Route19_Text_DouglasDefeat::
# 55 "data/maps/Route19_Frlg/scripts.pory"
	.string "Glub!$"

Route19_Text_DouglasPostBattle::
# 59 "data/maps/Route19_Frlg/scripts.pory"
	.string "I see a couple of islands over\n"
	.string "yonder!$"

Route19_Text_DavidIntro::
# 64 "data/maps/Route19_Frlg/scripts.pory"
	.string "I tried diving for POKéMON, but it\n"
	.string "was a no-go.$"

Route19_Text_DavidDefeat::
# 69 "data/maps/Route19_Frlg/scripts.pory"
	.string "Help!$"

Route19_Text_DavidPostBattle::
# 73 "data/maps/Route19_Frlg/scripts.pory"
	.string "I guess you have to fish for sea\n"
	.string "POKéMON.$"

Route19_Text_TonyIntro::
# 78 "data/maps/Route19_Frlg/scripts.pory"
	.string "I look at the sea to forget all\n"
	.string "the bad things that happened.$"

Route19_Text_TonyDefeat::
# 83 "data/maps/Route19_Frlg/scripts.pory"
	.string "Ooh!\n"
	.string "Traumatic!$"

Route19_Text_TonyPostBattle::
# 88 "data/maps/Route19_Frlg/scripts.pory"
	.string "I'm looking at the sea to forget\n"
	.string "the bad thing that happened!$"

Route19_Text_AnyaIntro::
# 93 "data/maps/Route19_Frlg/scripts.pory"
	.string "Oh, I just love your ride!\n"
	.string "Can I have it if I win?$"

Route19_Text_AnyaDefeat::
# 98 "data/maps/Route19_Frlg/scripts.pory"
	.string "Oh! I lost!$"

Route19_Text_AnyaPostBattle::
# 102 "data/maps/Route19_Frlg/scripts.pory"
	.string "It's still a long way to go to\n"
	.string "SEAFOAM ISLANDS…\p"
	.string "I want to go back to FUCHSIA…$"

Route19_Text_AliceIntro::
# 108 "data/maps/Route19_Frlg/scripts.pory"
	.string "Swimming's great!\n"
	.string "Sunburns aren't!$"

Route19_Text_AliceDefeat::
# 113 "data/maps/Route19_Frlg/scripts.pory"
	.string "Shocker!$"

Route19_Text_AlicePostBattle::
# 117 "data/maps/Route19_Frlg/scripts.pory"
	.string "My boyfriend wanted to swim to\n"
	.string "SEAFOAM ISLANDS.$"

Route19_Text_AxleIntro::
# 122 "data/maps/Route19_Frlg/scripts.pory"
	.string "Ahoy, there!\n"
	.string "These waters are treacherous!$"

Route19_Text_AxleDefeat::
# 127 "data/maps/Route19_Frlg/scripts.pory"
	.string "Ooh!\n"
	.string "Dangerous!$"

Route19_Text_AxlePostBattle::
# 132 "data/maps/Route19_Frlg/scripts.pory"
	.string "M-my legs! They cramped up!\n"
	.string "Glub, glub…$"

Route19_Text_ConnieIntro::
# 137 "data/maps/Route19_Frlg/scripts.pory"
	.string "I swam here with my friends…\n"
	.string "I'm tired…$"

Route19_Text_ConnieDefeat::
# 142 "data/maps/Route19_Frlg/scripts.pory"
	.string "I'm exhausted…$"

Route19_Text_ConniePostBattle::
# 146 "data/maps/Route19_Frlg/scripts.pory"
	.string "If I were to ride a POKéMON on\n"
	.string "the sea, I'd like a LAPRAS.\p"
	.string "LAPRAS is so big, I bet it\n"
	.string "would keep me dry on water.$"

Route19_Text_RouteSign::
# 153 "data/maps/Route19_Frlg/scripts.pory"
	.string "SEA ROUTE 19\n"
	.string "FUCHSIA CITY - SEAFOAM ISLANDS$"

Route19_Text_LiaIntro::
# 158 "data/maps/Route19_Frlg/scripts.pory"
	.string "LIA: I'm looking after my brother.\n"
	.string "He just became a TRAINER.$"

Route19_Text_LiaDefeat::
# 163 "data/maps/Route19_Frlg/scripts.pory"
	.string "LIA: That's no way to treat my\n"
	.string "little brother!$"

Route19_Text_LiaPostBattle::
# 168 "data/maps/Route19_Frlg/scripts.pory"
	.string "LIA: Do you have a younger\n"
	.string "brother?\p"
	.string "I hope you're teaching him all\n"
	.string "sorts of things.$"

Route19_Text_LiaNotEnoughMons::
# 175 "data/maps/Route19_Frlg/scripts.pory"
	.string "LIA: I want to battle together\n"
	.string "with my little brother.\p"
	.string "Don't you have two POKéMON?$"

Route19_Text_LucIntro::
# 181 "data/maps/Route19_Frlg/scripts.pory"
	.string "LUC: My big sis taught me how\n"
	.string "to swim and train POKéMON.$"

Route19_Text_LucDefeat::
# 186 "data/maps/Route19_Frlg/scripts.pory"
	.string "LUC: Oh, wow!\n"
	.string "Someone tougher than my big sis!$"

Route19_Text_LucPostBattle::
# 191 "data/maps/Route19_Frlg/scripts.pory"
	.string "LUC: My big sis is strong and nice.\n"
	.string "I think she's awesome!$"

Route19_Text_LucNotEnoughMons::
# 196 "data/maps/Route19_Frlg/scripts.pory"
	.string "LUC: I don't want to if I can't\n"
	.string "battle you with my big sis.\p"
	.string "Don't you have two POKéMON?$"
