Route21_North_Frlg_MapScripts::
	.byte 0


Route21_North_Text_RonaldIntro::
# 3 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "You want to know if the fish are\n"
	.string "biting?$"

Route21_North_Text_RonaldDefeat::
# 8 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "Dang!$"

Route21_North_Text_RonaldPostBattle::
# 12 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "I can't catch anything good.\n"
	.string "Not one good POKéMON to be had!$"

Route21_North_Text_WadeIntro::
# 17 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "I got a big haul!\n"
	.string "Wanna go for it?$"

Route21_North_Text_WadeDefeat::
# 22 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "Heheh, MAGIKARP just don't make\n"
	.string "the grade, do they?$"

Route21_North_Text_WadePostBattle::
# 27 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "I seem to only catch MAGIKARP!$"

Route21_North_Text_SpencerIntro::
# 31 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "The sea cleanses my body and soul!$"

Route21_North_Text_SpencerDefeat::
# 35 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle::
# 39 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "The sea is great and all, but I\n"
	.string "like the mountains, too.$"

Route21_North_Text_CueBallIntro::
# 44 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

Route21_North_Text_CueBallDefeat::
# 49 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "ぐわわ！$"

Route21_North_Text_CueBallPostBattle::
# 53 "data/maps/Route21_North_Frlg/scripts.pory"
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
