SSAnne_2F_Room6_Frlg_MapScripts::
	.byte 0


SSAnne_2F_Room6_EventScript_Woman1::
# 4 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room6_Text_CaptainIsAwfullySick, MSGBOX_NPC
	end


SSAnne_2F_Room6_EventScript_Woman2::
# 9 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	msgbox SSAnne_2F_Room6_Text_ManyPeopleGetSeasick, MSGBOX_NPC
	end


SSAnne_2F_Room6_Text_CaptainIsAwfullySick::
# 13 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	.string "The CAPTAIN said he's awfully sick.\n"
	.string "He was all pale.$"

SSAnne_2F_Room6_Text_ManyPeopleGetSeasick::
# 18 "data/maps/SSAnne_2F_Room6_Frlg/scripts.pory"
	.string "I hear many people get seasick.$"
