# 1 "data/maps/VictoryRoad_B1F/scripts.pory"

# 2 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_MapScripts::
# 3 "data/maps/VictoryRoad_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/VictoryRoad_B1F/scripts.pory"

# 5 "data/maps/VictoryRoad_B1F/scripts.pory"

# 6 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Samuel::
# 7 "data/maps/VictoryRoad_B1F/scripts.pory"
# 4 "data/maps/VictoryRoad_B1F/scripts.pory"
# 8 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_SAMUEL, VictoryRoad_B1F_Text_SamuelIntro, VictoryRoad_B1F_Text_SamuelDefeat
# 9 "data/maps/VictoryRoad_B1F/scripts.pory"
# 5 "data/maps/VictoryRoad_B1F/scripts.pory"
# 10 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_SamuelPostBattle, MSGBOX_AUTOCLOSE
# 11 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 12 "data/maps/VictoryRoad_B1F/scripts.pory"

# 13 "data/maps/VictoryRoad_B1F/scripts.pory"

# 14 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Shannon::
# 15 "data/maps/VictoryRoad_B1F/scripts.pory"
# 10 "data/maps/VictoryRoad_B1F/scripts.pory"
# 16 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_SHANNON, VictoryRoad_B1F_Text_ShannonIntro, VictoryRoad_B1F_Text_ShannonDefeat
# 17 "data/maps/VictoryRoad_B1F/scripts.pory"
# 11 "data/maps/VictoryRoad_B1F/scripts.pory"
# 18 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_ShannonPostBattle, MSGBOX_AUTOCLOSE
# 19 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 20 "data/maps/VictoryRoad_B1F/scripts.pory"

# 21 "data/maps/VictoryRoad_B1F/scripts.pory"

# 22 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Michelle::
# 23 "data/maps/VictoryRoad_B1F/scripts.pory"
# 16 "data/maps/VictoryRoad_B1F/scripts.pory"
# 24 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_MICHELLE, VictoryRoad_B1F_Text_MichelleIntro, VictoryRoad_B1F_Text_MichelleDefeat
# 25 "data/maps/VictoryRoad_B1F/scripts.pory"
# 17 "data/maps/VictoryRoad_B1F/scripts.pory"
# 26 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_MichellePostBattle, MSGBOX_AUTOCLOSE
# 27 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 28 "data/maps/VictoryRoad_B1F/scripts.pory"

# 29 "data/maps/VictoryRoad_B1F/scripts.pory"

# 30 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Mitchell::
# 31 "data/maps/VictoryRoad_B1F/scripts.pory"
# 22 "data/maps/VictoryRoad_B1F/scripts.pory"
# 32 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_MITCHELL, VictoryRoad_B1F_Text_MitchellIntro, VictoryRoad_B1F_Text_MitchellDefeat
# 33 "data/maps/VictoryRoad_B1F/scripts.pory"
# 23 "data/maps/VictoryRoad_B1F/scripts.pory"
# 34 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_MitchellPostBattle, MSGBOX_AUTOCLOSE
# 35 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 36 "data/maps/VictoryRoad_B1F/scripts.pory"

# 37 "data/maps/VictoryRoad_B1F/scripts.pory"

# 38 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_EventScript_Halle::
# 39 "data/maps/VictoryRoad_B1F/scripts.pory"
# 28 "data/maps/VictoryRoad_B1F/scripts.pory"
# 40 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_single TRAINER_HALLE, VictoryRoad_B1F_Text_HalleIntro, VictoryRoad_B1F_Text_HalleDefeat
# 41 "data/maps/VictoryRoad_B1F/scripts.pory"
# 29 "data/maps/VictoryRoad_B1F/scripts.pory"
# 42 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_HallePostBattle, MSGBOX_AUTOCLOSE
# 43 "data/maps/VictoryRoad_B1F/scripts.pory"
	end
# 44 "data/maps/VictoryRoad_B1F/scripts.pory"

# 45 "data/maps/VictoryRoad_B1F/scripts.pory"

# 46 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelIntro::
# 47 "data/maps/VictoryRoad_B1F/scripts.pory"
# 33 "data/maps/VictoryRoad_B1F/scripts.pory"
# 48 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "The thought that I'm getting closer to\n"
# 49 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "the POKéMON LEAGUE…\p"
# 50 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "I'm getting stage fright…$"
# 51 "data/maps/VictoryRoad_B1F/scripts.pory"

# 52 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelDefeat::
# 53 "data/maps/VictoryRoad_B1F/scripts.pory"
# 39 "data/maps/VictoryRoad_B1F/scripts.pory"
# 54 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "I couldn't do a thing…$"
# 55 "data/maps/VictoryRoad_B1F/scripts.pory"

# 56 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_SamuelPostBattle::
# 57 "data/maps/VictoryRoad_B1F/scripts.pory"
# 43 "data/maps/VictoryRoad_B1F/scripts.pory"
# 58 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "The POKéMON LEAGUE became distant\n"
# 59 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "again… What a letdown…$"
# 60 "data/maps/VictoryRoad_B1F/scripts.pory"

# 61 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonIntro::
# 62 "data/maps/VictoryRoad_B1F/scripts.pory"
# 48 "data/maps/VictoryRoad_B1F/scripts.pory"
# 63 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "To win your way through the POKéMON\n"
# 64 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "LEAGUE, you need the trust of your\l"
# 65 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "POKéMON.$"
# 66 "data/maps/VictoryRoad_B1F/scripts.pory"

# 67 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonDefeat::
# 68 "data/maps/VictoryRoad_B1F/scripts.pory"
# 54 "data/maps/VictoryRoad_B1F/scripts.pory"
# 69 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Your relationship is based on\n"
# 70 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "solid trust.$"
# 71 "data/maps/VictoryRoad_B1F/scripts.pory"

# 72 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_ShannonPostBattle::
# 73 "data/maps/VictoryRoad_B1F/scripts.pory"
# 59 "data/maps/VictoryRoad_B1F/scripts.pory"
# 74 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "By being together all the time, trust\n"
# 75 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "grows between POKéMON and TRAINERS.$"
# 76 "data/maps/VictoryRoad_B1F/scripts.pory"

# 77 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichelleIntro::
# 78 "data/maps/VictoryRoad_B1F/scripts.pory"
# 64 "data/maps/VictoryRoad_B1F/scripts.pory"
# 79 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "This isn't the goal. It's only a place\n"
# 80 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "on the way to the POKéMON LEAGUE.$"
# 81 "data/maps/VictoryRoad_B1F/scripts.pory"

# 82 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichelleDefeat::
# 83 "data/maps/VictoryRoad_B1F/scripts.pory"
# 69 "data/maps/VictoryRoad_B1F/scripts.pory"
# 84 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "That's the way!$"
# 85 "data/maps/VictoryRoad_B1F/scripts.pory"

# 86 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MichellePostBattle::
# 87 "data/maps/VictoryRoad_B1F/scripts.pory"
# 73 "data/maps/VictoryRoad_B1F/scripts.pory"
# 88 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "You'll do fine, for sure!\n"
# 89 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Your POKéMON are all eager to go!$"
# 90 "data/maps/VictoryRoad_B1F/scripts.pory"

# 91 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellIntro::
# 92 "data/maps/VictoryRoad_B1F/scripts.pory"
# 78 "data/maps/VictoryRoad_B1F/scripts.pory"
# 93 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "My POKéMON are cosmically\n"
# 94 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "awe inspiring!$"
# 95 "data/maps/VictoryRoad_B1F/scripts.pory"

# 96 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellDefeat::
# 97 "data/maps/VictoryRoad_B1F/scripts.pory"
# 83 "data/maps/VictoryRoad_B1F/scripts.pory"
# 98 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "I've never met anyone like you before.$"
# 99 "data/maps/VictoryRoad_B1F/scripts.pory"

# 100 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_MitchellPostBattle::
# 101 "data/maps/VictoryRoad_B1F/scripts.pory"
# 87 "data/maps/VictoryRoad_B1F/scripts.pory"
# 102 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Even outside of battle, I sense\n"
# 103 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "incredible power emanating from you\l"
# 104 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "and your POKéMON.$"
# 105 "data/maps/VictoryRoad_B1F/scripts.pory"

# 106 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HalleIntro::
# 107 "data/maps/VictoryRoad_B1F/scripts.pory"
# 93 "data/maps/VictoryRoad_B1F/scripts.pory"
# 108 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Okay, no need to get your back up!\n"
# 109 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Relax, let's take it easy!$"
# 110 "data/maps/VictoryRoad_B1F/scripts.pory"

# 111 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HalleDefeat::
# 112 "data/maps/VictoryRoad_B1F/scripts.pory"
# 98 "data/maps/VictoryRoad_B1F/scripts.pory"
# 113 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Whoa!\n"
# 114 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Wonderful!$"
# 115 "data/maps/VictoryRoad_B1F/scripts.pory"

# 116 "data/maps/VictoryRoad_B1F/scripts.pory"
VictoryRoad_B1F_Text_HallePostBattle::
# 117 "data/maps/VictoryRoad_B1F/scripts.pory"
# 103 "data/maps/VictoryRoad_B1F/scripts.pory"
# 118 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Sure, this is VICTORY ROAD.\p"
# 119 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "But it's not all that different from\n"
# 120 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "the path you've taken so far.\p"
# 121 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Try to enjoy things the rest of\n"
# 122 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "the way!$"
