PewterCity_House2_Frlg_MapScripts::
	.byte 0


PewterCity_House2_EventScript_OldMan::
# 4 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	msgbox PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow, MSGBOX_NPC
	end


PewterCity_House2_EventScript_LittleBoy::
# 9 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	msgbox PewterCity_House2_Text_MonsEasierCatchIfStatused, MSGBOX_NPC
	end


PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
# 13 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "POKéMON learn new techniques as\n"
	.string "they grow.\p"
	.string "But some moves must be taught to\n"
	.string "them by people.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
# 20 "data/maps/PewterCity_House2_Frlg/scripts.pory"
	.string "A POKéMON becomes easier to \n"
	.string "catch if it has a status problem.\p"
	.string "Sleep, poison, burn, or paralysis…\n"
	.string "Those are all effective.\p"
	.string "But catching POKéMON is never\n"
	.string "a sure thing!$"
