# 1 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"

# 2 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
CeladonCity_Condominiums_2F_Frlg_MapScripts::
# 3 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"

# 5 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"

# 6 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
CeladonCity_Condominiums_2F_EventScript_MeetingRoomSign::
# 7 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
# 4 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
# 8 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
	msgbox CeladonCity_Condominiums_2F_Text_GameFreakMeetingRoom, MSGBOX_SIGN
# 9 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
	end
# 10 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"

# 11 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"

# 12 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
CeladonCity_Condominiums_2F_Text_GameFreakMeetingRoom::
# 13 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
# 8 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
# 14 "data/maps/CeladonCity_Condominiums_2F_Frlg/scripts.pory"
	.string "GAME FREAK Meeting Room$"
