# 1 "data/maps/Route25_Frlg/scripts.pory"

# 2 "data/maps/Route25_Frlg/scripts.pory"
Route25_Frlg_MapScripts::
# 3 "data/maps/Route25_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route25_Frlg/scripts.pory"

# 5 "data/maps/Route25_Frlg/scripts.pory"

# 6 "data/maps/Route25_Frlg/scripts.pory"
Route25_EventScript_SeaCottageSign::
# 7 "data/maps/Route25_Frlg/scripts.pory"
# 4 "data/maps/Route25_Frlg/scripts.pory"
# 8 "data/maps/Route25_Frlg/scripts.pory"
	msgbox Route25_Text_SeaCottageSign, MSGBOX_SIGN
# 9 "data/maps/Route25_Frlg/scripts.pory"
	end
# 10 "data/maps/Route25_Frlg/scripts.pory"

# 11 "data/maps/Route25_Frlg/scripts.pory"

# 12 "data/maps/Route25_Frlg/scripts.pory"
Route25_EventScript_Man::
# 13 "data/maps/Route25_Frlg/scripts.pory"
# 9 "data/maps/Route25_Frlg/scripts.pory"
# 14 "data/maps/Route25_Frlg/scripts.pory"
	msgbox Route25_Text_AreYouHereAlone, MSGBOX_NPC
# 15 "data/maps/Route25_Frlg/scripts.pory"
	end
# 16 "data/maps/Route25_Frlg/scripts.pory"

# 17 "data/maps/Route25_Frlg/scripts.pory"

# 18 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_JoeyIntro::
# 19 "data/maps/Route25_Frlg/scripts.pory"
# 13 "data/maps/Route25_Frlg/scripts.pory"
# 20 "data/maps/Route25_Frlg/scripts.pory"
	.string "Local TRAINERS come here to\n"
# 21 "data/maps/Route25_Frlg/scripts.pory"
	.string "practice.$"
# 22 "data/maps/Route25_Frlg/scripts.pory"

# 23 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_JoeyDefeat::
# 24 "data/maps/Route25_Frlg/scripts.pory"
# 18 "data/maps/Route25_Frlg/scripts.pory"
# 25 "data/maps/Route25_Frlg/scripts.pory"
	.string "You're decent.$"
# 26 "data/maps/Route25_Frlg/scripts.pory"

# 27 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_JoeyPostBattle::
# 28 "data/maps/Route25_Frlg/scripts.pory"
# 22 "data/maps/Route25_Frlg/scripts.pory"
# 29 "data/maps/Route25_Frlg/scripts.pory"
	.string "All POKéMON have weaknesses.\n"
# 30 "data/maps/Route25_Frlg/scripts.pory"
	.string "Even the strongest ones.\p"
# 31 "data/maps/Route25_Frlg/scripts.pory"
	.string "That's why it's best to raise\n"
# 32 "data/maps/Route25_Frlg/scripts.pory"
	.string "POKéMON of different types.$"
# 33 "data/maps/Route25_Frlg/scripts.pory"

# 34 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_DanIntro::
# 35 "data/maps/Route25_Frlg/scripts.pory"
# 29 "data/maps/Route25_Frlg/scripts.pory"
# 36 "data/maps/Route25_Frlg/scripts.pory"
	.string "Dad took me to a great party on\n"
# 37 "data/maps/Route25_Frlg/scripts.pory"
	.string "the S.S. ANNE at VERMILION CITY.$"
# 38 "data/maps/Route25_Frlg/scripts.pory"

# 39 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_DanDefeat::
# 40 "data/maps/Route25_Frlg/scripts.pory"
# 34 "data/maps/Route25_Frlg/scripts.pory"
# 41 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm not mad!$"
# 42 "data/maps/Route25_Frlg/scripts.pory"

# 43 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_DanPostBattle::
# 44 "data/maps/Route25_Frlg/scripts.pory"
# 38 "data/maps/Route25_Frlg/scripts.pory"
# 45 "data/maps/Route25_Frlg/scripts.pory"
	.string "On the S.S. ANNE, I saw TRAINERS\n"
# 46 "data/maps/Route25_Frlg/scripts.pory"
	.string "from around the world.$"
# 47 "data/maps/Route25_Frlg/scripts.pory"

# 48 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_FlintIntro::
# 49 "data/maps/Route25_Frlg/scripts.pory"
# 43 "data/maps/Route25_Frlg/scripts.pory"
# 50 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm a cool guy.\n"
# 51 "data/maps/Route25_Frlg/scripts.pory"
	.string "I've got a girlfriend!$"
# 52 "data/maps/Route25_Frlg/scripts.pory"

# 53 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_FlintDefeat::
# 54 "data/maps/Route25_Frlg/scripts.pory"
# 48 "data/maps/Route25_Frlg/scripts.pory"
# 55 "data/maps/Route25_Frlg/scripts.pory"
	.string "Aww, darn…$"
# 56 "data/maps/Route25_Frlg/scripts.pory"

# 57 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_FlintPostBattle::
# 58 "data/maps/Route25_Frlg/scripts.pory"
# 52 "data/maps/Route25_Frlg/scripts.pory"
# 59 "data/maps/Route25_Frlg/scripts.pory"
	.string "Oh, well.\n"
# 60 "data/maps/Route25_Frlg/scripts.pory"
	.string "My girlfriend will cheer me up.$"
# 61 "data/maps/Route25_Frlg/scripts.pory"

# 62 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_KelseyIntro::
# 63 "data/maps/Route25_Frlg/scripts.pory"
# 57 "data/maps/Route25_Frlg/scripts.pory"
# 64 "data/maps/Route25_Frlg/scripts.pory"
	.string "Hi!\n"
# 65 "data/maps/Route25_Frlg/scripts.pory"
	.string "My boyfriend is cool!$"
# 66 "data/maps/Route25_Frlg/scripts.pory"

# 67 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_KelseyDefeat::
# 68 "data/maps/Route25_Frlg/scripts.pory"
# 62 "data/maps/Route25_Frlg/scripts.pory"
# 69 "data/maps/Route25_Frlg/scripts.pory"
	.string "My conditioning isn't the best…$"
# 70 "data/maps/Route25_Frlg/scripts.pory"

# 71 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_KelseyPostBattle::
# 72 "data/maps/Route25_Frlg/scripts.pory"
# 66 "data/maps/Route25_Frlg/scripts.pory"
# 73 "data/maps/Route25_Frlg/scripts.pory"
	.string "I wish my boyfriend was as good\n"
# 74 "data/maps/Route25_Frlg/scripts.pory"
	.string "as you.$"
# 75 "data/maps/Route25_Frlg/scripts.pory"

# 76 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_ChadIntro::
# 77 "data/maps/Route25_Frlg/scripts.pory"
# 71 "data/maps/Route25_Frlg/scripts.pory"
# 78 "data/maps/Route25_Frlg/scripts.pory"
	.string "I had this feeling…\n"
# 79 "data/maps/Route25_Frlg/scripts.pory"
	.string "I knew I had to battle you!$"
# 80 "data/maps/Route25_Frlg/scripts.pory"

# 81 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_ChadDefeat::
# 82 "data/maps/Route25_Frlg/scripts.pory"
# 76 "data/maps/Route25_Frlg/scripts.pory"
# 83 "data/maps/Route25_Frlg/scripts.pory"
	.string "I knew I'd lose, too!$"
# 84 "data/maps/Route25_Frlg/scripts.pory"

# 85 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_ChadPostBattle::
# 86 "data/maps/Route25_Frlg/scripts.pory"
# 80 "data/maps/Route25_Frlg/scripts.pory"
# 87 "data/maps/Route25_Frlg/scripts.pory"
	.string "If your POKéMON gets confused,\n"
# 88 "data/maps/Route25_Frlg/scripts.pory"
	.string "switch it out.\p"
# 89 "data/maps/Route25_Frlg/scripts.pory"
	.string "That's a good tactic.$"
# 90 "data/maps/Route25_Frlg/scripts.pory"

# 91 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_HaleyIntro::
# 92 "data/maps/Route25_Frlg/scripts.pory"
# 86 "data/maps/Route25_Frlg/scripts.pory"
# 93 "data/maps/Route25_Frlg/scripts.pory"
	.string "My friend has many cute POKéMON.\n"
# 94 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm so jealous!$"
# 95 "data/maps/Route25_Frlg/scripts.pory"

# 96 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_HaleyDefeat::
# 97 "data/maps/Route25_Frlg/scripts.pory"
# 91 "data/maps/Route25_Frlg/scripts.pory"
# 98 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm not so jealous!$"
# 99 "data/maps/Route25_Frlg/scripts.pory"

# 100 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_HaleyPostBattle::
# 101 "data/maps/Route25_Frlg/scripts.pory"
# 95 "data/maps/Route25_Frlg/scripts.pory"
# 102 "data/maps/Route25_Frlg/scripts.pory"
	.string "You came from MT. MOON?\n"
# 103 "data/maps/Route25_Frlg/scripts.pory"
	.string "May I have a CLEFAIRY?$"
# 104 "data/maps/Route25_Frlg/scripts.pory"

# 105 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_FranklinIntro::
# 106 "data/maps/Route25_Frlg/scripts.pory"
# 100 "data/maps/Route25_Frlg/scripts.pory"
# 107 "data/maps/Route25_Frlg/scripts.pory"
	.string "I just got down from MT. MOON,\n"
# 108 "data/maps/Route25_Frlg/scripts.pory"
	.string "but I've still got gas in the tank!$"
# 109 "data/maps/Route25_Frlg/scripts.pory"

# 110 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_FranklinDefeat::
# 111 "data/maps/Route25_Frlg/scripts.pory"
# 105 "data/maps/Route25_Frlg/scripts.pory"
# 112 "data/maps/Route25_Frlg/scripts.pory"
	.string "You worked hard!$"
# 113 "data/maps/Route25_Frlg/scripts.pory"

# 114 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_FranklinPostBattle::
# 115 "data/maps/Route25_Frlg/scripts.pory"
# 109 "data/maps/Route25_Frlg/scripts.pory"
# 116 "data/maps/Route25_Frlg/scripts.pory"
	.string "Drat!\n"
# 117 "data/maps/Route25_Frlg/scripts.pory"
	.string "A ZUBAT bit me back in that cave.$"
# 118 "data/maps/Route25_Frlg/scripts.pory"

# 119 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_NobIntro::
# 120 "data/maps/Route25_Frlg/scripts.pory"
# 114 "data/maps/Route25_Frlg/scripts.pory"
# 121 "data/maps/Route25_Frlg/scripts.pory"
	.string "I'm off to see a POKéMANIAC's\n"
# 122 "data/maps/Route25_Frlg/scripts.pory"
	.string "collection at the cape.$"
# 123 "data/maps/Route25_Frlg/scripts.pory"

# 124 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_NobDefeat::
# 125 "data/maps/Route25_Frlg/scripts.pory"
# 119 "data/maps/Route25_Frlg/scripts.pory"
# 126 "data/maps/Route25_Frlg/scripts.pory"
	.string "You done got me, and real good,\n"
# 127 "data/maps/Route25_Frlg/scripts.pory"
	.string "too!$"
# 128 "data/maps/Route25_Frlg/scripts.pory"

# 129 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_NobPostBattle::
# 130 "data/maps/Route25_Frlg/scripts.pory"
# 124 "data/maps/Route25_Frlg/scripts.pory"
# 131 "data/maps/Route25_Frlg/scripts.pory"
	.string "The POKéMANIAC sure lives up to\n"
# 132 "data/maps/Route25_Frlg/scripts.pory"
	.string "his name.\p"
# 133 "data/maps/Route25_Frlg/scripts.pory"
	.string "His collection includes many rare\n"
# 134 "data/maps/Route25_Frlg/scripts.pory"
	.string "species of POKéMON.$"
# 135 "data/maps/Route25_Frlg/scripts.pory"

# 136 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_WayneIntro::
# 137 "data/maps/Route25_Frlg/scripts.pory"
# 131 "data/maps/Route25_Frlg/scripts.pory"
# 138 "data/maps/Route25_Frlg/scripts.pory"
	.string "You're going to see BILL?\n"
# 139 "data/maps/Route25_Frlg/scripts.pory"
	.string "First, we battle!$"
# 140 "data/maps/Route25_Frlg/scripts.pory"

# 141 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_WayneDefeat::
# 142 "data/maps/Route25_Frlg/scripts.pory"
# 136 "data/maps/Route25_Frlg/scripts.pory"
# 143 "data/maps/Route25_Frlg/scripts.pory"
	.string "You're something.$"
# 144 "data/maps/Route25_Frlg/scripts.pory"

# 145 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_WaynePostBattle::
# 146 "data/maps/Route25_Frlg/scripts.pory"
# 140 "data/maps/Route25_Frlg/scripts.pory"
# 147 "data/maps/Route25_Frlg/scripts.pory"
	.string "The trail below is a shortcut to\n"
# 148 "data/maps/Route25_Frlg/scripts.pory"
	.string "CERULEAN CITY.$"
# 149 "data/maps/Route25_Frlg/scripts.pory"

# 150 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_SeaCottageSign::
# 151 "data/maps/Route25_Frlg/scripts.pory"
# 145 "data/maps/Route25_Frlg/scripts.pory"
# 152 "data/maps/Route25_Frlg/scripts.pory"
	.string "SEA COTTAGE\n"
# 153 "data/maps/Route25_Frlg/scripts.pory"
	.string "BILL lives here!$"
# 154 "data/maps/Route25_Frlg/scripts.pory"

# 155 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_MistyHighHopesAboutThisPlace::
# 156 "data/maps/Route25_Frlg/scripts.pory"
# 150 "data/maps/Route25_Frlg/scripts.pory"
# 157 "data/maps/Route25_Frlg/scripts.pory"
	.string "This cape is a famous date spot.\p"
# 158 "data/maps/Route25_Frlg/scripts.pory"
	.string "MISTY, the GYM LEADER, has high\n"
# 159 "data/maps/Route25_Frlg/scripts.pory"
	.string "hopes about this place.$"
# 160 "data/maps/Route25_Frlg/scripts.pory"

# 161 "data/maps/Route25_Frlg/scripts.pory"
Route25_Text_AreYouHereAlone::
# 162 "data/maps/Route25_Frlg/scripts.pory"
# 156 "data/maps/Route25_Frlg/scripts.pory"
# 163 "data/maps/Route25_Frlg/scripts.pory"
	.string "Hello, are you here alone?\p"
# 164 "data/maps/Route25_Frlg/scripts.pory"
	.string "If you're out at CERULEAN's cape…\n"
# 165 "data/maps/Route25_Frlg/scripts.pory"
	.string "Well, it should be as a couple.$"
