Route6_Frlg_MapScripts::
	.byte 0


Route6_EventScript_UndergroundPathSign::
# 4 "data/maps/Route6_Frlg/scripts.pory"
	msgbox Route6_Text_UndergroundPathSign, MSGBOX_SIGN
	end


Route6_Text_RickyIntro::
# 8 "data/maps/Route6_Frlg/scripts.pory"
	.string "Who's there?\n"
	.string "Quit listening in on us!$"

Route6_Text_RickyDefeat::
# 13 "data/maps/Route6_Frlg/scripts.pory"
	.string "I just can't win!$"

Route6_Text_RickyPostBattle::
# 17 "data/maps/Route6_Frlg/scripts.pory"
	.string "Whisper…\n"
	.string "Whisper…$"

Route6_Text_NancyIntro::
# 22 "data/maps/Route6_Frlg/scripts.pory"
	.string "Excuse me!\n"
	.string "This is a private conversation!$"

Route6_Text_NancyDefeat::
# 27 "data/maps/Route6_Frlg/scripts.pory"
	.string "Ugh!\n"
	.string "I hate losing.$"

Route6_Text_NancyPostBattle::
# 32 "data/maps/Route6_Frlg/scripts.pory"
	.string "Whisper…\n"
	.string "Whisper…$"

Route6_Text_KeigoIntro::
# 37 "data/maps/Route6_Frlg/scripts.pory"
	.string "There aren't many bugs out here.$"

Route6_Text_KeigoDefeat::
# 41 "data/maps/Route6_Frlg/scripts.pory"
	.string "No!\n"
	.string "You're kidding!$"

Route6_Text_KeigoPostBattle::
# 46 "data/maps/Route6_Frlg/scripts.pory"
	.string "I like bugs, so I'm going back to\n"
	.string "VIRIDIAN FOREST.$"

Route6_Text_JeffIntro::
# 51 "data/maps/Route6_Frlg/scripts.pory"
	.string "Huh?\n"
	.string "You want to talk to me?$"

Route6_Text_JeffDefeat::
# 56 "data/maps/Route6_Frlg/scripts.pory"
	.string "This stinks…\n"
	.string "I couldn't beat your challenge…$"

Route6_Text_JeffPostBattle::
# 61 "data/maps/Route6_Frlg/scripts.pory"
	.string "I should bring more POKéMON with\n"
	.string "me. I'll feel safer that way.$"

Route6_Text_IsabelleIntro::
# 66 "data/maps/Route6_Frlg/scripts.pory"
	.string "Me?\n"
	.string "Well, okay. I'll play!$"

Route6_Text_IsabelleDefeat::
# 71 "data/maps/Route6_Frlg/scripts.pory"
	.string "Things just didn't work…$"

Route6_Text_IsabellePostBattle::
# 75 "data/maps/Route6_Frlg/scripts.pory"
	.string "I want to get stronger.\n"
	.string "What's your secret?$"

Route6_Text_ElijahIntro::
# 80 "data/maps/Route6_Frlg/scripts.pory"
	.string "I've never seen you around.\n"
	.string "Are you good?$"

Route6_Text_ElijahDefeat::
# 85 "data/maps/Route6_Frlg/scripts.pory"
	.string "You're too good!$"

Route6_Text_ElijahPostBattle::
# 89 "data/maps/Route6_Frlg/scripts.pory"
	.string "Are my POKéMON weak?\n"
	.string "Or, am I just bad?\l"
	.string "Which do you think?$"

Route6_Text_UndergroundPathSign::
# 95 "data/maps/Route6_Frlg/scripts.pory"
	.string "UNDERGROUND PATH\n"
	.string "CERULEAN CITY - VERMILION CITY$"
