# 1 "data/maps/PetalburgCity_House2/scripts.pory"

# 2 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_MapScripts::
# 3 "data/maps/PetalburgCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/PetalburgCity_House2/scripts.pory"

# 5 "data/maps/PetalburgCity_House2/scripts.pory"

# 6 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_EventScript_Woman::
# 7 "data/maps/PetalburgCity_House2/scripts.pory"
# 4 "data/maps/PetalburgCity_House2/scripts.pory"
# 8 "data/maps/PetalburgCity_House2/scripts.pory"
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
# 9 "data/maps/PetalburgCity_House2/scripts.pory"
	end
# 10 "data/maps/PetalburgCity_House2/scripts.pory"

# 11 "data/maps/PetalburgCity_House2/scripts.pory"

# 12 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_EventScript_SchoolKid::
# 13 "data/maps/PetalburgCity_House2/scripts.pory"
# 9 "data/maps/PetalburgCity_House2/scripts.pory"
# 14 "data/maps/PetalburgCity_House2/scripts.pory"
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
# 15 "data/maps/PetalburgCity_House2/scripts.pory"
	end
# 16 "data/maps/PetalburgCity_House2/scripts.pory"

# 17 "data/maps/PetalburgCity_House2/scripts.pory"

# 18 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_Text_NormanBecameGymLeader::
# 19 "data/maps/PetalburgCity_House2/scripts.pory"
# 13 "data/maps/PetalburgCity_House2/scripts.pory"
# 20 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "NORMAN became our town's new\n"
# 21 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "GYM LEADER.\p"
# 22 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "I think he called his family over from\n"
# 23 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "somewhere far away.$"
# 24 "data/maps/PetalburgCity_House2/scripts.pory"

# 25 "data/maps/PetalburgCity_House2/scripts.pory"
PetalburgCity_House2_Text_BattledNormanOnce::
# 26 "data/maps/PetalburgCity_House2/scripts.pory"
# 20 "data/maps/PetalburgCity_House2/scripts.pory"
# 27 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "I battled NORMAN once, but, whew,\n"
# 28 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "he was way too strong.\p"
# 29 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "How would I put it?\p"
# 30 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "I just got the feeling that he\n"
# 31 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "lives for POKéMON.$"
