# 1 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"

# 2 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
TrainerTower_Roof_Frlg_MapScripts::
# 3 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
# 2 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
# 4 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, TrainerTower_OnResume
# 5 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
# 3 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
# 6 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TrainerTower_OnFrame
# 7 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
	.byte 0
# 8 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"

# 9 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"

# 10 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
TrainerTower_Roof_EventScript_Owner::
# 11 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
# 7 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
# 12 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
	call TrainerTower_EventScript_SpeakToOwner
# 13 "data/maps/TrainerTower_Roof_Frlg/scripts.pory"
	end
