SafariZone_East_Frlg_MapScripts::
	.byte 0


SafariZone_East_EventScript_RestHouseSign::
# 4 "data/maps/SafariZone_East_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_RestHouse, MSGBOX_SIGN
	end


SafariZone_East_EventScript_TrainerTips::
# 9 "data/maps/SafariZone_East_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk, MSGBOX_SIGN
	end


SafariZone_East_EventScript_AreaSign::
# 14 "data/maps/SafariZone_East_Frlg/scripts.pory"
	msgbox SafariZone_East_Text_AreaSign, MSGBOX_SIGN
	end


SafariZone_East_Text_RestHouse::
# 18 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "REST HOUSE$"

SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk::
# 22 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The remaining time declines only\n"
	.string "while you walk.$"

SafariZone_East_Text_AreaSign::
# 28 "data/maps/SafariZone_East_Frlg/scripts.pory"
	.string "AREA 1\n"
	.string "WEST: CENTER AREA$"
