# 1 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 2 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_Frlg_MapScripts::
# 3 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 5 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 6 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_Man::
# 7 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 4 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 8 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
# 9 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 10 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 11 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 12 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_OldMan::
# 13 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 9 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 14 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
# 15 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 16 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 17 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 18 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_Scientist::
# 19 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 14 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 20 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
# 21 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 22 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 23 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 24 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_LittleGirl::
# 25 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 19 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 26 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
# 27 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 28 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 29 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 30 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_BaldingMan::
# 31 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 24 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 32 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
# 33 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 34 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 35 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 36 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_SpaceShuttle::
# 37 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 29 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 38 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
# 39 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 40 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 41 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 42 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_2F_EventScript_MoonStone::
# 43 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 34 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 44 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
# 45 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	end
# 46 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 47 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 48 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
Text_SeismicTossTeach::
# 49 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 38 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 50 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "The secrets of space…\n"
# 51 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "The mysteries of earth…\p"
# 52 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "There are so many things about\n"
# 53 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "which we know so little.\p"
# 54 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "But that should spur us to study\n"
# 55 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "harder, not toss in the towel.\p"
# 56 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "The only thing you should toss…\p"
# 57 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Well, how about SEISMIC TOSS?\n"
# 58 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Should I teach that to a POKéMON?$"
# 59 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 60 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
Text_SeismicTossDeclined::
# 61 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 50 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 62 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Is that so?\n"
# 63 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I'm sure you'll be back for it.$"
# 64 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 65 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
Text_SeismicTossWhichMon::
# 66 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 55 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 67 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Which POKéMON wants to learn\n"
# 68 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "SEISMIC TOSS?$"
# 69 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 70 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
Text_SeismicTossTaught::
# 71 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 60 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 72 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I hope you won't toss in the towel.\n"
# 73 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Keep it up.$"
# 74 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 75 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
# 76 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 65 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 77 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "MOON STONE, huh?\p"
# 78 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "What's so special about it?\n"
# 79 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Looks like an ordinary rock to me.$"
# 80 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 81 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
# 82 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 71 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 83 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "July 20, 1969!\p"
# 84 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Humankind first set foot on the\n"
# 85 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "moon that day.\p"
# 86 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I bought a color TV just so I\n"
# 87 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "could watch that news.$"
# 88 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 89 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
# 90 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 79 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 91 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "This month, we're running a space\n"
# 92 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "exhibit.$"
# 93 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 94 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
# 95 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 84 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 96 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I want a PIKACHU!\n"
# 97 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "It's so cute!\p"
# 98 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "I asked my daddy to catch me one!$"
# 99 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 100 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_PikachuSoonIPromise::
# 101 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 90 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 102 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Yeah, a PIKACHU soon, I promise!$"
# 103 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 104 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_SpaceShuttle::
# 105 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 94 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 106 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "Space Shuttle$"
# 107 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"

# 108 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
# 109 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 98 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
# 110 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "A meteorite that fell on MT. MOON.\n"
# 111 "data/maps/PewterCity_Museum_2F_Frlg/scripts.pory"
	.string "It is thought to be a MOON STONE.$"
