# 1 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"

# 2 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_SouthEntrance_Frlg_MapScripts::
# 3 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"

# 5 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"

# 6 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_SouthEntrance_EventScript_Woman1::
# 7 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
# 4 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
# 8 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	msgbox Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze, MSGBOX_NPC
# 9 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	end
# 10 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"

# 11 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"

# 12 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_SouthEntrance_EventScript_Woman2::
# 13 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
# 9 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
# 14 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	msgbox Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite, MSGBOX_NPC
# 15 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	end
# 16 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"

# 17 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"

# 18 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
# 19 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
# 13 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
# 20 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	.string "Are you going to VIRIDIAN FOREST?\n"
# 21 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	.string "It's a natural maze in there.\l"
# 22 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	.string "Be careful you don't get lost.$"
# 23 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"

# 24 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
# 25 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
# 19 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
# 26 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	.string "RATTATA may be small, but don't\n"
# 27 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	.string "underestimate its wicked bite.\p"
# 28 "data/maps/Route2_ViridianForest_SouthEntrance_Frlg/scripts.pory"
	.string "Have you caught one already?$"
