UndergroundPath_SouthEntrance_Frlg_MapScripts::
	.byte 0


UndergroundPath_SouthEntrance_EventScript_Woman::
# 4 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
	msgbox UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness, MSGBOX_NPC
	end


UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness::
# 8 "data/maps/UndergroundPath_SouthEntrance_Frlg/scripts.pory"
	.string "People often lose things in the\n"
	.string "darkness of the UNDERGROUND PATH.$"
