# 1 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"

# 2 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
FiveIsland_LostCave_Entrance_Frlg_MapScripts::
# 3 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
# 2 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
# 4 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FiveIsland_LostCave_Entrance_OnTransition
# 5 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
	.byte 0
# 6 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"

# 7 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"

# 8 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
FiveIsland_LostCave_Entrance_OnTransition::
# 9 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
# 6 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
# 10 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
	setworldmapflag FLAG_WORLD_MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE
# 11 "data/maps/FiveIsland_LostCave_Entrance_Frlg/scripts.pory"
	end
