# 1 "data/maps/Route3_Frlg/scripts.pory"

# 2 "data/maps/Route3_Frlg/scripts.pory"
Route3_Frlg_MapScripts::
# 3 "data/maps/Route3_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/Route3_Frlg/scripts.pory"

# 5 "data/maps/Route3_Frlg/scripts.pory"

# 6 "data/maps/Route3_Frlg/scripts.pory"
Route3_EventScript_Youngster::
# 7 "data/maps/Route3_Frlg/scripts.pory"
# 4 "data/maps/Route3_Frlg/scripts.pory"
# 8 "data/maps/Route3_Frlg/scripts.pory"
	msgbox Route3_Text_TunnelFromCeruleanTiring, MSGBOX_NPC
# 9 "data/maps/Route3_Frlg/scripts.pory"
	end
# 10 "data/maps/Route3_Frlg/scripts.pory"

# 11 "data/maps/Route3_Frlg/scripts.pory"

# 12 "data/maps/Route3_Frlg/scripts.pory"
Route3_EventScript_RouteSign::
# 13 "data/maps/Route3_Frlg/scripts.pory"
# 9 "data/maps/Route3_Frlg/scripts.pory"
# 14 "data/maps/Route3_Frlg/scripts.pory"
	msgbox Route3_Text_RouteSign, MSGBOX_SIGN
# 15 "data/maps/Route3_Frlg/scripts.pory"
	end
# 16 "data/maps/Route3_Frlg/scripts.pory"

# 17 "data/maps/Route3_Frlg/scripts.pory"

# 18 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_TunnelFromCeruleanTiring::
# 19 "data/maps/Route3_Frlg/scripts.pory"
# 13 "data/maps/Route3_Frlg/scripts.pory"
# 20 "data/maps/Route3_Frlg/scripts.pory"
	.string "Whew… I better take a rest…\n"
# 21 "data/maps/Route3_Frlg/scripts.pory"
	.string "Groan…\p"
# 22 "data/maps/Route3_Frlg/scripts.pory"
	.string "That tunnel from CERULEAN takes a\n"
# 23 "data/maps/Route3_Frlg/scripts.pory"
	.string "lot out of you!$"
# 24 "data/maps/Route3_Frlg/scripts.pory"

# 25 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_ColtonIntro::
# 26 "data/maps/Route3_Frlg/scripts.pory"
# 20 "data/maps/Route3_Frlg/scripts.pory"
# 27 "data/maps/Route3_Frlg/scripts.pory"
	.string "Hey!\n"
# 28 "data/maps/Route3_Frlg/scripts.pory"
	.string "I saw you in VIRIDIAN FOREST!$"
# 29 "data/maps/Route3_Frlg/scripts.pory"

# 30 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_ColtonDefeat::
# 31 "data/maps/Route3_Frlg/scripts.pory"
# 25 "data/maps/Route3_Frlg/scripts.pory"
# 32 "data/maps/Route3_Frlg/scripts.pory"
	.string "You beat me again!$"
# 33 "data/maps/Route3_Frlg/scripts.pory"

# 34 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_ColtonPostBattle::
# 35 "data/maps/Route3_Frlg/scripts.pory"
# 29 "data/maps/Route3_Frlg/scripts.pory"
# 36 "data/maps/Route3_Frlg/scripts.pory"
	.string "There are other kinds of POKéMON\n"
# 37 "data/maps/Route3_Frlg/scripts.pory"
	.string "than the ones you find in forests.$"
# 38 "data/maps/Route3_Frlg/scripts.pory"

# 39 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_BenIntro::
# 40 "data/maps/Route3_Frlg/scripts.pory"
# 34 "data/maps/Route3_Frlg/scripts.pory"
# 41 "data/maps/Route3_Frlg/scripts.pory"
	.string "Hi!\n"
# 42 "data/maps/Route3_Frlg/scripts.pory"
	.string "I like shorts!\p"
# 43 "data/maps/Route3_Frlg/scripts.pory"
	.string "They're delightfully comfy and\n"
# 44 "data/maps/Route3_Frlg/scripts.pory"
	.string "easy to wear!$"
# 45 "data/maps/Route3_Frlg/scripts.pory"

# 46 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_BenDefeat::
# 47 "data/maps/Route3_Frlg/scripts.pory"
# 41 "data/maps/Route3_Frlg/scripts.pory"
# 48 "data/maps/Route3_Frlg/scripts.pory"
	.string "I don't believe it!$"
# 49 "data/maps/Route3_Frlg/scripts.pory"

# 50 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_BenPostBattle::
# 51 "data/maps/Route3_Frlg/scripts.pory"
# 45 "data/maps/Route3_Frlg/scripts.pory"
# 52 "data/maps/Route3_Frlg/scripts.pory"
	.string "Are you using a POKéMON CENTER's\n"
# 53 "data/maps/Route3_Frlg/scripts.pory"
	.string "PC for storing your POKéMON?\p"
# 54 "data/maps/Route3_Frlg/scripts.pory"
	.string "Each BOX can hold up to\n"
# 55 "data/maps/Route3_Frlg/scripts.pory"
	.string "30 POKéMON.$"
# 56 "data/maps/Route3_Frlg/scripts.pory"

# 57 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_JaniceIntro::
# 58 "data/maps/Route3_Frlg/scripts.pory"
# 52 "data/maps/Route3_Frlg/scripts.pory"
# 59 "data/maps/Route3_Frlg/scripts.pory"
	.string "Excuse me!\n"
# 60 "data/maps/Route3_Frlg/scripts.pory"
	.string "You looked at me, didn't you?$"
# 61 "data/maps/Route3_Frlg/scripts.pory"

# 62 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_JaniceDefeat::
# 63 "data/maps/Route3_Frlg/scripts.pory"
# 57 "data/maps/Route3_Frlg/scripts.pory"
# 64 "data/maps/Route3_Frlg/scripts.pory"
	.string "You're mean!$"
# 65 "data/maps/Route3_Frlg/scripts.pory"

# 66 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_JanicePostBattle::
# 67 "data/maps/Route3_Frlg/scripts.pory"
# 61 "data/maps/Route3_Frlg/scripts.pory"
# 68 "data/maps/Route3_Frlg/scripts.pory"
	.string "You shouldn't be staring if you\n"
# 69 "data/maps/Route3_Frlg/scripts.pory"
	.string "don't want to battle!$"
# 70 "data/maps/Route3_Frlg/scripts.pory"

# 71 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_GregIntro::
# 72 "data/maps/Route3_Frlg/scripts.pory"
# 66 "data/maps/Route3_Frlg/scripts.pory"
# 73 "data/maps/Route3_Frlg/scripts.pory"
	.string "Are you a TRAINER?\n"
# 74 "data/maps/Route3_Frlg/scripts.pory"
	.string "Let's get with it right away!$"
# 75 "data/maps/Route3_Frlg/scripts.pory"

# 76 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_GregDefeat::
# 77 "data/maps/Route3_Frlg/scripts.pory"
# 71 "data/maps/Route3_Frlg/scripts.pory"
# 78 "data/maps/Route3_Frlg/scripts.pory"
	.string "If I had new POKéMON, I would've\n"
# 79 "data/maps/Route3_Frlg/scripts.pory"
	.string "won!$"
# 80 "data/maps/Route3_Frlg/scripts.pory"

# 81 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_GregPostBattle::
# 82 "data/maps/Route3_Frlg/scripts.pory"
# 76 "data/maps/Route3_Frlg/scripts.pory"
# 83 "data/maps/Route3_Frlg/scripts.pory"
	.string "If a POKéMON BOX on the PC gets\n"
# 84 "data/maps/Route3_Frlg/scripts.pory"
	.string "full, just switch to another BOX.$"
# 85 "data/maps/Route3_Frlg/scripts.pory"

# 86 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_SallyIntro::
# 87 "data/maps/Route3_Frlg/scripts.pory"
# 81 "data/maps/Route3_Frlg/scripts.pory"
# 88 "data/maps/Route3_Frlg/scripts.pory"
	.string "That look you gave me…\n"
# 89 "data/maps/Route3_Frlg/scripts.pory"
	.string "It's so intriguing!$"
# 90 "data/maps/Route3_Frlg/scripts.pory"

# 91 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_SallyDefeat::
# 92 "data/maps/Route3_Frlg/scripts.pory"
# 86 "data/maps/Route3_Frlg/scripts.pory"
# 93 "data/maps/Route3_Frlg/scripts.pory"
	.string "Be nice!$"
# 94 "data/maps/Route3_Frlg/scripts.pory"

# 95 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_SallyPostBattle::
# 96 "data/maps/Route3_Frlg/scripts.pory"
# 90 "data/maps/Route3_Frlg/scripts.pory"
# 97 "data/maps/Route3_Frlg/scripts.pory"
	.string "You can avoid battles by not\n"
# 98 "data/maps/Route3_Frlg/scripts.pory"
	.string "letting TRAINERS see you.$"
# 99 "data/maps/Route3_Frlg/scripts.pory"

# 100 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_CalvinIntro::
# 101 "data/maps/Route3_Frlg/scripts.pory"
# 95 "data/maps/Route3_Frlg/scripts.pory"
# 102 "data/maps/Route3_Frlg/scripts.pory"
	.string "Hey! You're not wearing shorts!\n"
# 103 "data/maps/Route3_Frlg/scripts.pory"
	.string "What's wrong with you?$"
# 104 "data/maps/Route3_Frlg/scripts.pory"

# 105 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_CalvinDefeat::
# 106 "data/maps/Route3_Frlg/scripts.pory"
# 100 "data/maps/Route3_Frlg/scripts.pory"
# 107 "data/maps/Route3_Frlg/scripts.pory"
	.string "Lost!\n"
# 108 "data/maps/Route3_Frlg/scripts.pory"
	.string "Lost! Lost!$"
# 109 "data/maps/Route3_Frlg/scripts.pory"

# 110 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_CalvinPostBattle::
# 111 "data/maps/Route3_Frlg/scripts.pory"
# 105 "data/maps/Route3_Frlg/scripts.pory"
# 112 "data/maps/Route3_Frlg/scripts.pory"
	.string "I always wear shorts, even in\n"
# 113 "data/maps/Route3_Frlg/scripts.pory"
	.string "winter. That's my policy.$"
# 114 "data/maps/Route3_Frlg/scripts.pory"

# 115 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_JamesIntro::
# 116 "data/maps/Route3_Frlg/scripts.pory"
# 110 "data/maps/Route3_Frlg/scripts.pory"
# 117 "data/maps/Route3_Frlg/scripts.pory"
	.string "I'll battle you with the POKéMON\n"
# 118 "data/maps/Route3_Frlg/scripts.pory"
	.string "I just caught.$"
# 119 "data/maps/Route3_Frlg/scripts.pory"

# 120 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_JamesDefeat::
# 121 "data/maps/Route3_Frlg/scripts.pory"
# 115 "data/maps/Route3_Frlg/scripts.pory"
# 122 "data/maps/Route3_Frlg/scripts.pory"
	.string "Done like dinner!$"
# 123 "data/maps/Route3_Frlg/scripts.pory"

# 124 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_JamesPostBattle::
# 125 "data/maps/Route3_Frlg/scripts.pory"
# 119 "data/maps/Route3_Frlg/scripts.pory"
# 126 "data/maps/Route3_Frlg/scripts.pory"
	.string "Trained POKéMON are stronger than\n"
# 127 "data/maps/Route3_Frlg/scripts.pory"
	.string "the wild ones.$"
# 128 "data/maps/Route3_Frlg/scripts.pory"

# 129 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_RobinIntro::
# 130 "data/maps/Route3_Frlg/scripts.pory"
# 124 "data/maps/Route3_Frlg/scripts.pory"
# 131 "data/maps/Route3_Frlg/scripts.pory"
	.string "Eek!\n"
# 132 "data/maps/Route3_Frlg/scripts.pory"
	.string "Did you touch me?$"
# 133 "data/maps/Route3_Frlg/scripts.pory"

# 134 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_RobinDefeat::
# 135 "data/maps/Route3_Frlg/scripts.pory"
# 129 "data/maps/Route3_Frlg/scripts.pory"
# 136 "data/maps/Route3_Frlg/scripts.pory"
	.string "That's it?$"
# 137 "data/maps/Route3_Frlg/scripts.pory"

# 138 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_RobinPostBattle::
# 139 "data/maps/Route3_Frlg/scripts.pory"
# 133 "data/maps/Route3_Frlg/scripts.pory"
# 140 "data/maps/Route3_Frlg/scripts.pory"
	.string "ROUTE 4 is at the foot of\n"
# 141 "data/maps/Route3_Frlg/scripts.pory"
	.string "MT. MOON.$"
# 142 "data/maps/Route3_Frlg/scripts.pory"

# 143 "data/maps/Route3_Frlg/scripts.pory"
Route3_Text_RouteSign::
# 144 "data/maps/Route3_Frlg/scripts.pory"
# 138 "data/maps/Route3_Frlg/scripts.pory"
# 145 "data/maps/Route3_Frlg/scripts.pory"
	.string "ROUTE 3\n"
# 146 "data/maps/Route3_Frlg/scripts.pory"
	.string "MT. MOON AHEAD$"
