# 1 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"

# 2 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
AbandonedShip_Rooms2_B1F_MapScripts::
# 3 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
	.byte 0
# 4 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"

# 5 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"

# 6 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
AbandonedShip_Rooms2_B1F_EventScript_Camper::
# 7 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
# 5 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
# 8 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
# 9 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
	end
# 10 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"

# 11 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"

# 12 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring::
# 13 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
# 9 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
# 14 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
	.string "This is a perfect place to go exploring!\n"
# 15 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
	.string "It's exciting here!\p"
# 16 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
	.string "I bet there're amazing treasures on\n"
# 17 "data/maps/AbandonedShip_Rooms2_B1F/scripts.pory"
	.string "board.$"
