# 1 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
SSAnne_1F_Room3_Frlg_MapScripts::
# 3 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 6 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
SSAnne_1F_Room3_EventScript_LittleGirl::
# 7 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 4 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 8 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	msgbox SSAnne_1F_Room3_Text_AlwaysTravelWithWigglytuff, MSGBOX_NPC
# 9 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	end
# 10 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 11 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 12 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
SSAnne_1F_Room3_EventScript_BaldingMan::
# 13 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 9 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 14 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	msgbox SSAnne_1F_Room3_Text_CruiseIsElegantAndCozy, MSGBOX_NPC
# 15 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	end
# 16 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 17 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 18 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
SSAnne_1F_Room3_EventScript_Wigglytuff::
# 19 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 14 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 20 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	lock
# 21 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 15 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 22 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	faceplayer
# 23 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 16 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 24 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	waitse
# 25 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 17 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 26 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	playmoncry SPECIES_WIGGLYTUFF, CRY_MODE_NORMAL
# 27 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 18 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 28 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	msgbox SSAnne_1F_Room3_Text_Wigglytuff
# 29 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 19 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 30 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	waitmoncry
# 31 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 20 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 32 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	release
# 33 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	end
# 34 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 35 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 36 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
SSAnne_1F_Room3_Text_CruiseIsElegantAndCozy::
# 37 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 24 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 38 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	.string "A world cruise is so elegant yet\n"
# 39 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	.string "cozy!$"
# 40 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 41 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
SSAnne_1F_Room3_Text_AlwaysTravelWithWigglytuff::
# 42 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 29 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 43 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	.string "I always travel with WIGGLYTUFF.\n"
# 44 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	.string "I never leave home without it.$"
# 45 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"

# 46 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
SSAnne_1F_Room3_Text_Wigglytuff::
# 47 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 34 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
# 48 "data/maps/SSAnne_1F_Room3_Frlg/scripts.pory"
	.string "WIGGLYTUFF: Puup pupuu!$"
