# 1 "data/maps/VictoryRoad_B2F/scripts.pory"

# 2 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_MapScripts::
# 3 "data/maps/VictoryRoad_B2F/scripts.pory"
	.byte 0
# 4 "data/maps/VictoryRoad_B2F/scripts.pory"

# 5 "data/maps/VictoryRoad_B2F/scripts.pory"

# 6 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Vito::
# 7 "data/maps/VictoryRoad_B2F/scripts.pory"
# 4 "data/maps/VictoryRoad_B2F/scripts.pory"
# 8 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_VITO, VictoryRoad_B2F_Text_VitoIntro, VictoryRoad_B2F_Text_VitoDefeat
# 9 "data/maps/VictoryRoad_B2F/scripts.pory"
# 5 "data/maps/VictoryRoad_B2F/scripts.pory"
# 10 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_VitoPostBattle, MSGBOX_AUTOCLOSE
# 11 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 12 "data/maps/VictoryRoad_B2F/scripts.pory"

# 13 "data/maps/VictoryRoad_B2F/scripts.pory"

# 14 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Owen::
# 15 "data/maps/VictoryRoad_B2F/scripts.pory"
# 10 "data/maps/VictoryRoad_B2F/scripts.pory"
# 16 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_OWEN, VictoryRoad_B2F_Text_OwenIntro, VictoryRoad_B2F_Text_OwenDefeat
# 17 "data/maps/VictoryRoad_B2F/scripts.pory"
# 11 "data/maps/VictoryRoad_B2F/scripts.pory"
# 18 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_OwenPostBattle, MSGBOX_AUTOCLOSE
# 19 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 20 "data/maps/VictoryRoad_B2F/scripts.pory"

# 21 "data/maps/VictoryRoad_B2F/scripts.pory"

# 22 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Caroline::
# 23 "data/maps/VictoryRoad_B2F/scripts.pory"
# 16 "data/maps/VictoryRoad_B2F/scripts.pory"
# 24 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_CAROLINE, VictoryRoad_B2F_Text_CarolineIntro, VictoryRoad_B2F_Text_CarolineDefeat
# 25 "data/maps/VictoryRoad_B2F/scripts.pory"
# 17 "data/maps/VictoryRoad_B2F/scripts.pory"
# 26 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_CarolinePostBattle, MSGBOX_AUTOCLOSE
# 27 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 28 "data/maps/VictoryRoad_B2F/scripts.pory"

# 29 "data/maps/VictoryRoad_B2F/scripts.pory"

# 30 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Julie::
# 31 "data/maps/VictoryRoad_B2F/scripts.pory"
# 22 "data/maps/VictoryRoad_B2F/scripts.pory"
# 32 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_JULIE, VictoryRoad_B2F_Text_JulieIntro, VictoryRoad_B2F_Text_JulieDefeat
# 33 "data/maps/VictoryRoad_B2F/scripts.pory"
# 23 "data/maps/VictoryRoad_B2F/scripts.pory"
# 34 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_JuliePostBattle, MSGBOX_AUTOCLOSE
# 35 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 36 "data/maps/VictoryRoad_B2F/scripts.pory"

# 37 "data/maps/VictoryRoad_B2F/scripts.pory"

# 38 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Felix::
# 39 "data/maps/VictoryRoad_B2F/scripts.pory"
# 28 "data/maps/VictoryRoad_B2F/scripts.pory"
# 40 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_FELIX, VictoryRoad_B2F_Text_FelixIntro, VictoryRoad_B2F_Text_FelixDefeat
# 41 "data/maps/VictoryRoad_B2F/scripts.pory"
# 29 "data/maps/VictoryRoad_B2F/scripts.pory"
# 42 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_FelixPostBattle, MSGBOX_AUTOCLOSE
# 43 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 44 "data/maps/VictoryRoad_B2F/scripts.pory"

# 45 "data/maps/VictoryRoad_B2F/scripts.pory"

# 46 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_EventScript_Dianne::
# 47 "data/maps/VictoryRoad_B2F/scripts.pory"
# 34 "data/maps/VictoryRoad_B2F/scripts.pory"
# 48 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_single TRAINER_DIANNE, VictoryRoad_B2F_Text_DianneIntro, VictoryRoad_B2F_Text_DianneDefeat
# 49 "data/maps/VictoryRoad_B2F/scripts.pory"
# 35 "data/maps/VictoryRoad_B2F/scripts.pory"
# 50 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_DiannePostBattle, MSGBOX_AUTOCLOSE
# 51 "data/maps/VictoryRoad_B2F/scripts.pory"
	end
# 52 "data/maps/VictoryRoad_B2F/scripts.pory"

# 53 "data/maps/VictoryRoad_B2F/scripts.pory"

# 54 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoIntro::
# 55 "data/maps/VictoryRoad_B2F/scripts.pory"
# 39 "data/maps/VictoryRoad_B2F/scripts.pory"
# 56 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I trained together with my whole family,\n"
# 57 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "every one of us!\l"
# 58 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I'm not losing to anyone!$"
# 59 "data/maps/VictoryRoad_B2F/scripts.pory"

# 60 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoDefeat::
# 61 "data/maps/VictoryRoad_B2F/scripts.pory"
# 45 "data/maps/VictoryRoad_B2F/scripts.pory"
# 62 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Better than my family?!\n"
# 63 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Is that possible?!$"
# 64 "data/maps/VictoryRoad_B2F/scripts.pory"

# 65 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_VitoPostBattle::
# 66 "data/maps/VictoryRoad_B2F/scripts.pory"
# 50 "data/maps/VictoryRoad_B2F/scripts.pory"
# 67 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I was better than everyone in my\n"
# 68 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "family. I've never lost before…\p"
# 69 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I've lost my confidence…\n"
# 70 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Maybe I'll go home…$"
# 71 "data/maps/VictoryRoad_B2F/scripts.pory"

# 72 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenIntro::
# 73 "data/maps/VictoryRoad_B2F/scripts.pory"
# 57 "data/maps/VictoryRoad_B2F/scripts.pory"
# 74 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I'd heard that there was a tough\n"
# 75 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "little kid around. Do they mean you?$"
# 76 "data/maps/VictoryRoad_B2F/scripts.pory"

# 77 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenDefeat::
# 78 "data/maps/VictoryRoad_B2F/scripts.pory"
# 62 "data/maps/VictoryRoad_B2F/scripts.pory"
# 79 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The little shrimp is tough!$"
# 80 "data/maps/VictoryRoad_B2F/scripts.pory"

# 81 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_OwenPostBattle::
# 82 "data/maps/VictoryRoad_B2F/scripts.pory"
# 66 "data/maps/VictoryRoad_B2F/scripts.pory"
# 83 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The rumors I heard, that tough little\n"
# 84 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "kid is from PETALBURG CITY.$"
# 85 "data/maps/VictoryRoad_B2F/scripts.pory"

# 86 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolineIntro::
# 87 "data/maps/VictoryRoad_B2F/scripts.pory"
# 71 "data/maps/VictoryRoad_B2F/scripts.pory"
# 88 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You must be getting a little tired.$"
# 89 "data/maps/VictoryRoad_B2F/scripts.pory"

# 90 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolineDefeat::
# 91 "data/maps/VictoryRoad_B2F/scripts.pory"
# 75 "data/maps/VictoryRoad_B2F/scripts.pory"
# 92 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "No signs of tiring at all!$"
# 93 "data/maps/VictoryRoad_B2F/scripts.pory"

# 94 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_CarolinePostBattle::
# 95 "data/maps/VictoryRoad_B2F/scripts.pory"
# 79 "data/maps/VictoryRoad_B2F/scripts.pory"
# 96 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "VICTORY ROAD and the POKéMON LEAGUE\n"
# 97 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "are long and grueling challenges.\l"
# 98 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Beware of fatigue!$"
# 99 "data/maps/VictoryRoad_B2F/scripts.pory"

# 100 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JulieIntro::
# 101 "data/maps/VictoryRoad_B2F/scripts.pory"
# 85 "data/maps/VictoryRoad_B2F/scripts.pory"
# 102 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You shouldn't get complacent just\n"
# 103 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "because you have a lot of GYM BADGES.\p"
# 104 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "There's always going to be someone\n"
# 105 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "who's better than you!$"
# 106 "data/maps/VictoryRoad_B2F/scripts.pory"

# 107 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JulieDefeat::
# 108 "data/maps/VictoryRoad_B2F/scripts.pory"
# 92 "data/maps/VictoryRoad_B2F/scripts.pory"
# 109 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You're better than me!$"
# 110 "data/maps/VictoryRoad_B2F/scripts.pory"

# 111 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_JuliePostBattle::
# 112 "data/maps/VictoryRoad_B2F/scripts.pory"
# 96 "data/maps/VictoryRoad_B2F/scripts.pory"
# 113 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Gaze on your collected BADGES and\n"
# 114 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "remember the TRAINERS you've faced.$"
# 115 "data/maps/VictoryRoad_B2F/scripts.pory"

# 116 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixIntro::
# 117 "data/maps/VictoryRoad_B2F/scripts.pory"
# 101 "data/maps/VictoryRoad_B2F/scripts.pory"
# 118 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I've come this far, but the tension's\n"
# 119 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "giving me awful stomach pain…$"
# 120 "data/maps/VictoryRoad_B2F/scripts.pory"

# 121 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixDefeat::
# 122 "data/maps/VictoryRoad_B2F/scripts.pory"
# 106 "data/maps/VictoryRoad_B2F/scripts.pory"
# 123 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Ooh…\n"
# 124 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "It hurts…$"
# 125 "data/maps/VictoryRoad_B2F/scripts.pory"

# 126 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_FelixPostBattle::
# 127 "data/maps/VictoryRoad_B2F/scripts.pory"
# 111 "data/maps/VictoryRoad_B2F/scripts.pory"
# 128 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I can't help getting all tense knowing\n"
# 129 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "that I'm nearing the POKéMON LEAGUE.\p"
# 130 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "It's all I can do to feign calm.$"
# 131 "data/maps/VictoryRoad_B2F/scripts.pory"

# 132 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DianneIntro::
# 133 "data/maps/VictoryRoad_B2F/scripts.pory"
# 117 "data/maps/VictoryRoad_B2F/scripts.pory"
# 134 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The elite among the elite gather in\n"
# 135 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "this cave.\p"
# 136 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "How are you finding it?$"
# 137 "data/maps/VictoryRoad_B2F/scripts.pory"

# 138 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DianneDefeat::
# 139 "data/maps/VictoryRoad_B2F/scripts.pory"
# 123 "data/maps/VictoryRoad_B2F/scripts.pory"
# 140 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Not rattled in the least bit!$"
# 141 "data/maps/VictoryRoad_B2F/scripts.pory"

# 142 "data/maps/VictoryRoad_B2F/scripts.pory"
VictoryRoad_B2F_Text_DiannePostBattle::
# 143 "data/maps/VictoryRoad_B2F/scripts.pory"
# 127 "data/maps/VictoryRoad_B2F/scripts.pory"
# 144 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You do have guts! I like that!\n"
# 145 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Keep it going!$"
