# 1 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 2 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_Frlg_MapScripts::
# 3 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 5 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 6 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_EventScript_Leonard::
# 7 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 4 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 8 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	trainerbattle_single TRAINER_SAILOR_LEONARD, SSAnne_B1F_Room4_Text_LeonardIntro, SSAnne_B1F_Room4_Text_LeonardDefeat
# 9 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 5 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 10 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	msgbox SSAnne_B1F_Room4_Text_LeonardPostBattle, MSGBOX_AUTOCLOSE
# 11 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	end
# 12 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 13 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 14 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_EventScript_Duncan::
# 15 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 10 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 16 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	trainerbattle_single TRAINER_SAILOR_DUNCAN, SSAnne_B1F_Room4_Text_DuncanIntro, SSAnne_B1F_Room4_Text_DuncanDefeat
# 17 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 11 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 18 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	msgbox SSAnne_B1F_Room4_Text_DuncanPostBattle, MSGBOX_AUTOCLOSE
# 19 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	end
# 20 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 21 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 22 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_Text_LeonardIntro::
# 23 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 15 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 24 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "You know what they say about\n"
# 25 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "sailors and battling!$"
# 26 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 27 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_Text_LeonardDefeat::
# 28 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 20 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 29 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "Right!\n"
# 30 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "Good battle, mate!$"
# 31 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 32 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_Text_LeonardPostBattle::
# 33 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 25 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 34 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "Hahaha!\n"
# 35 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "Want to be a sailor, mate?$"
# 36 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 37 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_Text_DuncanIntro::
# 38 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 30 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 39 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "Come on, then!\n"
# 40 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "My sailor's pride is at stake!$"
# 41 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 42 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_Text_DuncanDefeat::
# 43 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 35 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 44 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "Your spirit sank me!$"
# 45 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"

# 46 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
SSAnne_B1F_Room4_Text_DuncanPostBattle::
# 47 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 39 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
# 48 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "Did you see the FISHING GURU in\n"
# 49 "data/maps/SSAnne_B1F_Room4_Frlg/scripts.pory"
	.string "VERMILION CITY?$"
