# 1 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 2 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Frlg_MapScripts::
# 3 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 5 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 6 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker1::
# 7 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 4 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 8 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
# 9 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	end
# 10 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 11 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 12 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker2::
# 13 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 9 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 14 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
# 15 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	end
# 16 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 17 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 18 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker3::
# 19 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 14 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 20 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
# 21 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	end
# 22 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 23 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 24 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_EventScript_Worker4::
# 25 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 19 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 26 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
# 27 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	end
# 28 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 29 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 30 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
# 31 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 23 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 32 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "We nicknamed the WARDEN\n"
# 33 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "“SLOWPOKE.”\p"
# 34 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "You know, he has that vacant look\n"
# 35 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "like a SLOWPOKE.$"
# 36 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 37 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
# 38 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 30 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 39 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "WARDEN SLOWPOKE is very\n"
# 40 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "knowledgeable about POKéMON.\p"
# 41 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "He even has some fossils of rare,\n"
# 42 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "extinct POKéMON.$"
# 43 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 44 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
# 45 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 37 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 46 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "WARDEN SLOWPOKE came in, but\n"
# 47 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "I couldn't understand him.\p"
# 48 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "I think he's got a speech problem!$"
# 49 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"

# 50 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
# 51 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 43 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
# 52 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "WARDEN SLOWPOKE is running a\n"
# 53 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "promotion campaign right now.\p"
# 54 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "Try to get to the farthest corner\n"
# 55 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "of the SAFARI ZONE.\p"
# 56 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "If you can make it, you'll win a\n"
# 57 "data/maps/FuchsiaCity_SafariZone_Office_Frlg/scripts.pory"
	.string "very convenient prize.$"
