# 1 "data/maps/SixIsland_House_Frlg/scripts.pory"

# 2 "data/maps/SixIsland_House_Frlg/scripts.pory"
SixIsland_House_Frlg_MapScripts::
# 3 "data/maps/SixIsland_House_Frlg/scripts.pory"
	.byte 0
# 4 "data/maps/SixIsland_House_Frlg/scripts.pory"

# 5 "data/maps/SixIsland_House_Frlg/scripts.pory"

# 6 "data/maps/SixIsland_House_Frlg/scripts.pory"
SixIsland_House_EventScript_OldMan::
# 7 "data/maps/SixIsland_House_Frlg/scripts.pory"
# 4 "data/maps/SixIsland_House_Frlg/scripts.pory"
# 8 "data/maps/SixIsland_House_Frlg/scripts.pory"
	msgbox SixIsland_House_Text_GoodPlaceForNatureAndHistory, MSGBOX_NPC
# 9 "data/maps/SixIsland_House_Frlg/scripts.pory"
	end
# 10 "data/maps/SixIsland_House_Frlg/scripts.pory"

# 11 "data/maps/SixIsland_House_Frlg/scripts.pory"

# 12 "data/maps/SixIsland_House_Frlg/scripts.pory"
SixIsland_House_Text_GoodPlaceForNatureAndHistory::
# 13 "data/maps/SixIsland_House_Frlg/scripts.pory"
# 8 "data/maps/SixIsland_House_Frlg/scripts.pory"
# 14 "data/maps/SixIsland_House_Frlg/scripts.pory"
	.string "There's nothing that young people'd\n"
# 15 "data/maps/SixIsland_House_Frlg/scripts.pory"
	.string "find exciting here on this island.\p"
# 16 "data/maps/SixIsland_House_Frlg/scripts.pory"
	.string "But, this is a good place in terms\n"
# 17 "data/maps/SixIsland_House_Frlg/scripts.pory"
	.string "of nature and history.\p"
# 18 "data/maps/SixIsland_House_Frlg/scripts.pory"
	.string "Relax and enjoy your stay.$"
